### ISSUE TITLE
Allow more than three roles for Oracle monitoring

### ISSUE THREAD

**Issue by virkunen** [ikzelf/zbxdb#100]
Hello,

First of all, thanks a lot for such a great tool, that saved a lot of time implementing the DB monitoring.

There were some problems faced while connecting to Oracle with specific role. After checking the oracle.py it has been noticed that only three roles are possible to be defined: SYSDBA, SYSASM and normal.

In my case SYSBKP would need to be used, so I suggest to make it flexible in defining this parameter in the config.

This is the patch I would have proposed via the pull request, though got 403 with permission reject from this repo:

```
def connect(_db, _c):
    """the actual connect"""

--    if _c['role'].upper() == "SYSASM":
--        _c['omode'] = _db.SYSASM

--    if _c['role'].upper() == "SYSDBA":
--        _c['omode'] = _db.SYSDBA

++    if _c['role'].upper() != 'NORMAL':
++       _c['omode'] = getattr(_db,_c['role'])
```

As you can see, it converts the "role" config string to the attribute, while keeping the "normal" role when set.

Please check if it goes in-line with your architecture.

Thanks again.

Best regards,
Vitaly

**Comment by ikzelf** [comment]
Thanks for the patch, I just pushed it. Strange that a pull request did not work since I am not aware of blocking that. On the contrary, I invite to create them.
Thanks!
