### ISSUE TITLE
Need to change Thin mode to Thick mode oracledb (10g)

### ISSUE THREAD

**Issue by MKH-Beldi** [ikzelf/zbxdb#103]
I have a problem with oracledb that cannot connect to my Oracle 10g instance because oracledb thin mode does not support NNE (Native Network Encryption). 
Can you suggest a solution without changing anything in my Oracle instance? I need to change oracledb mode from Thin mode to Thick mode.

![image](https://github.com/ikzelf/zbxdb/assets/65089678/63e38e3f-1901-4d39-a67e-06978a9964ee)

**Comment by ikzelf** [comment]
Easiest is to switch back to the CXoracle 8.3 Python driver with the oracle instant client libraries. That should support most of sqlnet. From what I see in [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enablingthick) the new oracle Python driver needs an extra client initialization call that CXoracle did not need.

**Comment by MKH-Beldi** [comment]
I tried to switch to cx_Oracle, but unfortunately, it doesn't support Oracle 10g; it supports versions 11.2 and above.
![image](https://github.com/ikzelf/zbxdb/assets/65089678/c41fc708-3862-4cfe-8f21-b6e196416f8d)

**Comment by ikzelf** [comment]
In that case, download a newer version of the oracle client libraries. You seem to have a v10 library but need from v11.2. There is a good chance it also connects to a v10 database.

**Comment by MKH-Beldi** [comment]
It works! by replacing oracle client v10 with v11. However, not all queries are working as expected, as shown in the image below.

![image](https://github.com/ikzelf/zbxdb/assets/65089678/a83f1370-11fe-4e04-998f-3332f2efb89c)

After verification in Zabbix, I found that some metrics or items have nodata, as shown in the image below.

![image](https://github.com/ikzelf/zbxdb/assets/65089678/cbd88492-ba1c-44bf-a14c-0546c69daff9)

There are also metrics that are working:

![image](https://github.com/ikzelf/zbxdb/assets/65089678/846de630-ef9b-4b67-875b-45f40b902446)

The question that arises is whether the metrics that did not work because I used oracle client v11 and my Oracle instance is v10, or is it something else.

I appreciate your help and your time, a big thank you.

**Comment by ikzelf** [comment]
Check your config for the site specific templates. You kept the example for ebs in the config which obviously only works if you have that apps objects in your database. Remove that from your config.
There is quite a bit of selfmonitoring in zbxdb. Check in zabbix, in latest data the zbxdb application. That lists the queries, their status and some metrics about the queries.
For me, it looks like it works as expected.

**Comment by MKH-Beldi** [comment]
I really appreciate your help and your great work for this third-party Zabbix Oracle monitoring. All in works know, which for how have the same problem can be resolved with this conversation.
