### ISSUE TITLE
rds_stat.py file is not identifying db class db.r6i.4xlarge.tpc2.mem2x

### ISSUE THREAD

**Issue by udhairajarem** [ikzelf/zbxdb#104]
Hello Team,

The rds_stat.py file is not identifying the new db class instance db.r6i.4xlarge.tpc2.mem2x. If we try to strip & replace option the Allocated Memory shows a static value of 128 GB not matter whatever size the Memory is used. If we check the Storage Space sometimes it gives the right info, but of the times static or wrong values. Copy of Code attached along with the changed code.
[Original Script.zip](https://github.com/user-attachments/files/16372289/Original.Script.zip)
[Changed Script.zip](https://github.com/user-attachments/files/16372290/Changed.Script.zip)
Any suggestion please

**Comment by ikzelf** [comment]
I fail to see/find what this has to do with monitoring databases using sql and zbxdb for zabbix.
my suggestion is to report in the correct project.
