### ISSUE TITLE
zbxdb plugin reboots

### ISSUE THREAD

**Issue by udhairajarem** [ikzelf/zbxdb#105]
@ikzelf 
Good Day!!!

We have multiple DB RDS's in different AWS Regions & all data is showing up, however the issue that we noticed of late is the plugin keeps rebooting without any reasons. I'm attaching the logs from 2 of the RDS's & the logs are repetitive. Kindly advice on this please.

[zbxdb Logs.zip](https://github.com/user-attachments/files/16833065/zbxdb.Logs.zip)

**Comment by ikzelf** [comment]
etc/zbxdb.facportal-k8s-prod-databasestack-dbinstance-1.cfg changed from 
Mon Sep  2 06:20:09 2024 to 
Mon Sep  2 06:21:05 2024 
restarting

the configuration file is constantly changing. At least, the last modified date does. This is a reason for zbxdb to restart. Make sure that this file is constant and zbxdb will be happy to keep running.

**Comment by udhairajarem** [comment]
Hello @ikzelf 

Thanks for the suggestion, did a further check as to why the config file is being replaced/modified found few queries missing in the zbxdb folder & corresponding trigger in UI. Fixed the same & all good now.
