### ISSUE TITLE
Template localization

### ISSUE THREAD

**Issue by fgprodigal** [ikzelf/zbxdb#15]
Some descriptions in template are not in English, could you please provide us an English verion, thank you! 😄

**Comment by ikzelf** [comment]
Sure, no problem, I just pushed an english version. I hope this is what you meant.

**Comment by fgprodigal** [comment]
That's it! Thanks for your job! You're really fast!

**Comment by fgprodigal** [comment]
Wait....

Import failed
Trigger prototype "dg[{#DGRP} loopt binnen 14d vol" depends on trigger "dg[{#DGRP} fills up within 2d", which does not exist.

**Comment by ikzelf** [comment]
That was 2 related errors. I  forgot to mention: I did not test it. Sorry but just pushed a -hopefully- better one.

**Comment by fgprodigal** [comment]
Import failed
Trigger prototype "p_ts[{#PDB}_{#TS_NAME}] fills up within 14d" depends on trigger "p_ts[{#PDB}_{#TS_NAME}] fills up within 5d", which does not exist.

**Comment by ikzelf** [comment]
Added translation for "p_ts[{#PDB}_{#TS_NAME}] loopt binnen 5d vol" 
I hope it is better now.

**Comment by fgprodigal** [comment]
It works this time, thanks again!

**Comment by ikzelf** [comment]
Glad I could help.
