### ISSUE TITLE
ZBXDB-1013: Db execution error: ORA-01013: ???????????

### ISSUE THREAD

**Issue by MichaelJochen** [ikzelf/zbxdb#16]
Hi
when I run the zbxdb.py with config file, The output contains success and also failure outputs, the errors seems, to be for frequency of mission planning and frequency of Sql execution,
the error is:
"
WARNING:__main__:zbxdb cancel_sql checks_60m p_ts
WARNING:__main__:zbxdb canceled   checks_60m p_ts
INFO:__main__:key=checks_60m.p_ts ZBXDB-1013: Db execution error: ORA-01013: ???????????
"
Sql execution time is about 1 to 2 minutes, the frequency of the mission plan I try to set to 1 or 2, it will go wrong (ZBXDB-1013).
How can I set the frequency of the above two?
Thank you, I look forward to your reply.

**Comment by MichaelJochen** [comment]
There is no garbled error on the following:
WARNING:__main__:zbxdb cancel_sql checks_60m p_ts
WARNING:__main__:zbxdb canceled   checks_60m p_ts
INFO:__main__:key=checks_60m.p_ts ZBXDB-1013: Db execution error: ORA-01013: user requested cancel of current operation

**Comment by MichaelJochen** [comment]
This error may also have been caused by a timeout in a sql pass-through query. To resolve this error, properties of the timeout parameter need to be changed to a higher value. 
So,Where is the setting?

**Comment by ikzelf** [comment]
Hi,
you can set the sql_timeout parameter in seconds, in the connection configuration file.
The p_ts query is a bit sensitive for up to date statistics. An sql trace can help to identify the cause.
Normally it runs in 1 to 2 seconds and sometimes it goes over 2 hours....
Check the tables that are part of dba_free_space to start with.

Groeten,
Ronald Rood

**Comment by ikzelf** [comment]
Where you able to reduce the runtime for this query?
You can easily pick this query from the etc/zbxdb_checks/oracle/primary.NN.cfg. Search for the query labeled with p_ts in the checks_60m section.

**Comment by MichaelJochen** [comment]
Thank you,Ronald, I started to study the dba_free_space view after I received your suggestion yesterday and found out that it is indeed the reason. After confirming with the application person today, I am ready to try to empty the recycle bin.

**Comment by ikzelf** [comment]
Last time I had this, I had to gather dictionary stats and fixed_objects_stats to get it back running again. If this alone does not get p_ts back in the seconds range ...
select text from dba_views where view_name = 'DBA_FREE_SPACE';
and check the fixed tables like sys.x$ktfbue that are in the  text. 
Run dbms_stats.gather_table_stats on them.

**Comment by ikzelf** [comment]
Hi Michael,
did you get this fixed?

**Comment by MichaelJochen** [comment]
Yes, it has been solved. The process is as follows:
SQL>  SELECT count(1) FROM dba_recyclebin;

  COUNT(1)
----------
      2770

SQL> purge dba_recyclebin;

DBA 回收站已清空。

SQL> set timing on
SQL> SELECT tablespace_name, SUM(bytes) free
  2    FROM dba_free_space
  3   GROUP BY tablespace_name;

TABLESPACE_NAME                      FREE
------------------------------ ----------
MYQDP                          1043070976
PMSTEST                        4293918720
DHEC_FUNCTION                  1061552128
SYSAUX                         1776025600
UNDOTBS1                       1.8171E+10
YYHGLRALA                       521273344
TBS_DHEC_YSJBXGL                103809024
TBS_DHEC_YFMH                   518520832
PLANDERUSER                    4846452736
MES                             790822912
TBS_ZHBX                        521011200

TABLESPACE_NAME                      FREE
------------------------------ ----------
TBS_ZHBX_1                      523108352
TBS_WLGC                        516423680
TBS_YJDD_1                       54919168
FINANCE1                        395575296
PWMS                            232128512
USERS                            71434240
PIDS                           1072693248
DHEC_TBS                        910426112
TBS_YYCR_1                      519897088
TBS_GZRZ_1                      521994240
SMS                             396689408

TABLESPACE_NAME                      FREE
------------------------------ ----------
ERPADMIN                       1036648448
TEST                             51380224
TBS_DHEC_MOM                    587137024
SYSTEM                          556990464
TBS_GGSJ_1                      224919552
DEQS                           1562181632
DHEC_SQS                        165019648
YKSPACE                        2510356480
TBS_MJZZ                        522584064
THAMS                           185466880
DHEC_DEQS_COSMO                  24903680

TABLESPACE_NAME                      FREE
------------------------------ ----------
UNDOTBS2                       9300803584
MESCHA                         1072627712
RUIJIAN                          82771968
PMS                            3406954496
SALE                           1072627712
CVJMES                         1072693248
TBS_FILE_1                      161153024
TBS_CXTJ_1                      522846208
LOGCHECK                        520093696
MYQDP3                         4293918720
DEQS_F                         1529937920

TABLESPACE_NAME                      FREE
------------------------------ ----------
TBS_FINANCE62_TEST             2143420416

已选择45行。

已用时间:  00: 00: 00.09
Groeten,
Michael

**Comment by ikzelf** [comment]
Nice, in that case I will close  this  issue. Thanks for reporting.

**Comment by ikzelf** [comment]
depends on how often  is defined ..... ;-) 
about daily
