### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

### ISSUE THREAD

**Issue by MichaelJochen** [ikzelf/zbxdb#18]
hi Ronald,when monitoring the sqlserver database with zbxdb, I encountered the following error:
"
2019-07-14 18:04:01.972193 user CISTATS CISTATS sid,serial 0,0 instance DHEC-VM-74 as normal cancel:False

INFO:__main__:using checks from ['etc/zbxdb_checks/mssql/primary.11.cfg']

INFO:__main__:checks loading etc/zbxdb_checks/mssql/primary.11.cfg

CRITICAL:__main__:file etc/zbxdb_checks/mssql/primary.11.cfg has parsing errors ->(13)

CRITICAL:__main__:problem
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 794, in <module>
    main()
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 539, in main
    sec_mins = int(_checks.get(section, "minutes"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
"
How can I analyze and resolve this issue?
Thank you, I look forward to your reply.

**Comment by ikzelf** [comment]
Hi,

I have no machine at hand now ... I could have made an error in primary.11.cfg, it should have section names containing a minutes parameter that should tell the frequency in minutes after which the queries in the given section should be repeated and the list of queries.

Can you compare with the other primary cfg files? I think it should be easy to spot.

Sorry for the inconvenience 

Groeten,
Ronald Rood

**Comment by MichaelJochen** [comment]
ok,and what is the name of the section?

**Comment by MichaelJochen** [comment]
well,i found it,at line 139 of mssql's primary.11.cfg
"
[checks_60m]
minutes: 60
instname: SELECT 'zbxdb[connect,instance_name]', @@servername
"
Remove
”[checks_60m]
Minutes: 60"
After that, there is no problem.

**Comment by ikzelf** [comment]
Thanks, I will see that I can fix that tomorrow, if time allows ....

Groeten,
Ronald Rood

**Comment by MichaelJochen** [comment]
Another question, which templates are made for mssql? Which one do I use to configure the web page?

**Comment by ikzelf** [comment]
I use the same for all.
Most items I created for oracle and where possible I try to reuse them for others. Like backups, storage, databases etc.

Groeten,
Ronald Rood
