### ISSUE TITLE
How to set db info with none default port in zbxdb config file ?

### ISSUE THREAD

**Issue by zliangbj** [ikzelf/zbxdb#22]
[zbxdb]
db_url = //localhost/fsdb01
username = postgres
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxora_out
hostname = testhost
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs
password_enc = cjB0cjAwdA==

Is there a filed to set the port if the db not using defautl port? thanks!

**Comment by zliangbj** [comment]
INFO:__main__:connecting to dbsnmp/******@//10.0.245.22:1526/fsscpdb1
I‘ve tried to set in cfg file like this: 
   db_url = //localhost:1526/fsdb01
and it returns error: 

WARNING:__main__:(4.1)connection error: [12514] ORA-12514: TNS:listener does not currently know of service requested in connect descriptor for dbsnmp@//localhost:1526/testdb

**Comment by ikzelf** [comment]
What you did was correct, regarding the setting of the port. You could use lsnrctl status or lsnrctl services to see which services are known by the listener.

**Comment by ikzelf** [comment]
did you get this working?
Do you have any tips to improve this?

**Comment by zliangbj** [comment]
Yes , it works. I made a spelling mistakes. Thanks!
