### ISSUE TITLE
INFO:__main__:key=checks_05m.fra ZBXDB-1476: Db execution error: ORA-01476: divisor is equal to zero

### ISSUE THREAD

**Issue by bjenmonk** [ikzelf/zbxdb#23]
INFO:__main__:key=checks_05m.fra ZBXDB-1476: Db execution error: ORA-01476: divisor is equal to zero
I am using the latest version and connect to oracle 12c

**Comment by bjenmonk** [comment]
I fixed it by changing 
select 'fra[usable,pct]',100-(100*(space_used - space_reclaimable)/space_limit)
to
select 'fra[usable,pct]',decode(space_limit, 0,0,(100-(100*(space_used - space_reclaimable)/space_limit)))

**Comment by ikzelf** [comment]
Thanks for the notification and even more for the fix.
