### ISSUE TITLE
zbxdb collecting data but not inserting into Zabbix

### ISSUE THREAD

**Issue by rlfink** [ikzelf/zbxdb#26]
My zbxdb installation is collecting data as I have seen the archive files.   However, I am not seeing any data in my Zabbix portal.   My cfg file is as follows:
[zbxdb]
db_url = //localhost/zabbix
username = zabbix_stat
password =
db_type = mssql
server = 10.10.16.12
server_port = 1433
db_name = master
db_driver = pytds
role = normal
out_dir = $ZBXDB_HOME/zbxdb_out
hostname = vserver15768
checks_dir = etc/zbxdb_checks
site_checks = NONE
# cafile = $HOME/somecapemfile
instance_type = rdbms

The hostname and IP address are of my mssql database server.  My Zabbix repository is on the localhost and obviously Mysql.  I created a host for the hostname above and linked to the template provided.   Why would I not see any data in Zabbix?   Thank you

**Comment by ikzelf** [comment]
Hi,
zbxdb is created with the idea of having many instances of zbxdb running and collecting data in the out_dir/ To send the data to zabbix you need to schedule zbxdb_sender.py that collects the data from out_dir/ and sends it to zabbix.
Did you miss the zbxdb_sender.py step?

**Comment by rlfink** [comment]
It is scheduled.   However, I keep getting this in the error log.

Wed Jan 29 18:45:01 UTC 2020
mv: cannot stat ‘/home/zbxdb/zbxdb_out/*’: No such file or directory
zbxdb.vserver15768.zbx /home/zbxdb/zbxdb_sender/in

The file does exist in that directory and is owned by the user (zbxdb) who runs the zbxdb.py process.

**Comment by rlfink** [comment]
[zbxdb@tc3vmdevus1 ~]$ ls -l zbxdb_out
total 24
-rw-rw-r-- 1 zbxdb zbxdb 22701 Jan 29 18:45 zbxdb.vserver15768.zbx

I have even tried changing the out_dir variable from what is listed above to a relevant directory:
out_dir = zbxdb_out

**Comment by ikzelf** [comment]
Hi Randy,
what is the contents of  /home/zbxdb/zbxdb_sender/ ?
The zbxdb_sender.py process tries to move the files from $ZBXDB_OUT to /home/zbxdb/zbxdb_sender/in/ from where the files are sent to zabbix, zipped and saved into /home/zbxdb/zbxdb_sender/archive/ for 2 days.
So, after sending the files, the in/ subdirectory should be empty and the contents should be in a timestamped file in the archive/ subdirectory in ~/zbxdb_sender/

**Comment by rlfink** [comment]
Hi Ron-
The /home/zbxdb/zbxdb_sender/ directory looks correct.  It has subdirectories for “in” and “archive”.   The “in” directory is empty.   The “archive” directory has tar and gzipped files for each run.

I’m having trouble understanding why it gives the error that it cannot “stat” the out directory.

**Comment by ikzelf** [comment]
Normally zbxdb is continually writing data to a file in out_dir. zbxdb_sender.py picks that data up once a minute. Given the fact that it created files in archive/ it tells me something is working. The default for zbxdb_sender.py is to send to the zabbix server on local host...

1) is the zabbix server on local host?
2) zabbix hostnames are case sensitive. Are the hostnames on zbxdb.*.cfg exactly the same as created in zabbix?

**Comment by rlfink** [comment]
Hi Ron-
Yes, Zabbix server is on the localhost.

The hostnames in zbxdb.*.cfg is the same as entered into Zabbix.   However, how am I supposed to enter individual databases within a Microsoft instance?   For example, my server that I am monitoring and which is pulling stats to the archive file is named vserver15768.   The instance name is MSSQLSERVER (default).   I then have individual databases such as “datahub”.   What is the correct method for entering that in zabbix host configuration?

Thanks

**Comment by rlfink** [comment]
One other thing that I am noticing.   My zbxdb_sender program has a command line as the following:
      cat $file | zabbix_sender -z 127.0.0.1 -T -i - | sed "s/^/$file /"

I do not have an executable named “zabbix_sender”.   I created a symlink to zbxdb_sender.   Am I missing an executable or did what I do with the symlink acceptable?

**Comment by ikzelf** [comment]
Hi Randy,
your hostname should be your instance name (in the case of mssql) and the databases are auto discovered.
Yes, you miss the zabbix_sender executable. You need to install that first. This might need some better error handling/reporting I guess .....

**Comment by rlfink** [comment]
There doesn’t seem to be a zabbix_sender program in the github master branch, which is where I obtained the files.

As for the hostname being the instance name, this would be an issue since the default instance name for all SQL Servers is MSSQLSERVER.   I wouldn’t be able to distinguish between non-prod and prod databases.

**Comment by ikzelf** [comment]
The zabbix_sender is a zabbix tool. If you compile zabbix from source it should be installed.
sudo yum info zabbix-sender

**Comment by rlfink** [comment]
Thank you for the help on Zabbix_sender.  I installed it and am now seeing a little data in Zabbix.   I had created hosts named after an individual database name (datahub), the instance name (MSSQLSERVER), and the host name (vserver15768).  I am now seeing a little data under the host name.

I do see some metrics under the Zabbix Latest Data screen.  However, I am not seeing any data.   I am guessing it is related to errors that I see in the zbxdb_sender log.   Below is a sample.

zbxdb.vserver15768.zbx zabbix_sender [110599]: DEBUG: answer [{"response":"success","info":"processed: 123; failed: 127; total: 250; seconds spent: 0.001989"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 123; failed: 127; total: 250; seconds spent: 0.001989"
zbxdb.vserver15768.zbx zabbix_sender [110600]: DEBUG: answer [{"response":"success","info":"processed: 82; failed: 168; total: 250; seconds spent: 0.001629"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 82; failed: 168; total: 250; seconds spent: 0.001629"
zbxdb.vserver15768.zbx zabbix_sender [110601]: DEBUG: answer [{"response":"success","info":"processed: 116; failed: 134; total: 250; seconds spent: 0.001866"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 116; failed: 134; total: 250; seconds spent: 0.001866"
zbxdb.vserver15768.zbx zabbix_sender [110602]: DEBUG: answer [{"response":"success","info":"processed: 4; failed: 2; total: 6; seconds spent: 0.000078"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 4; failed: 2; total: 6; seconds spent: 0.000078"
zbxdb.vserver15768.zbx sent: 1506; skipped: 0; total: 1506

Any ideas?

Thanks again for your help.  I feel that I am getting pretty close.

**Comment by rlfink** [comment]
I am now starting to see some data for each database, particularly rman, db, inst, inst.parm, and zbxdb sections.

I am still curious about the failed entries in the zbxdb_sender log noted in my earlier email.

From: Randy Fink
Sent: Thursday, January 30, 2020 2:38 PM
To: ikzelf/zbxdb <reply@reply.github.com>; ikzelf/zbxdb <zbxdb@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ikzelf/zbxdb] zbxdb collecting data but not inserting into Zabbix (#26)

Thank you for the help on Zabbix_sender.  I installed it and am now seeing a little data in Zabbix.   I had created hosts named after an individual database name (datahub), the instance name (MSSQLSERVER), and the host name (vserver15768).  I am now seeing a little data under the host name.

I do see some metrics under the Zabbix Latest Data screen.  However, I am not seeing any data.   I am guessing it is related to errors that I see in the zbxdb_sender log.   Below is a sample.

zbxdb.vserver15768.zbx zabbix_sender [110599]: DEBUG: answer [{"response":"success","info":"processed: 123; failed: 127; total: 250; seconds spent: 0.001989"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 123; failed: 127; total: 250; seconds spent: 0.001989"
zbxdb.vserver15768.zbx zabbix_sender [110600]: DEBUG: answer [{"response":"success","info":"processed: 82; failed: 168; total: 250; seconds spent: 0.001629"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 82; failed: 168; total: 250; seconds spent: 0.001629"
zbxdb.vserver15768.zbx zabbix_sender [110601]: DEBUG: answer [{"response":"success","info":"processed: 116; failed: 134; total: 250; seconds spent: 0.001866"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 116; failed: 134; total: 250; seconds spent: 0.001866"
zbxdb.vserver15768.zbx zabbix_sender [110602]: DEBUG: answer [{"response":"success","info":"processed: 4; failed: 2; total: 6; seconds spent: 0.000078"}]
zbxdb.vserver15768.zbx Response from "127.0.0.1:10051": "processed: 4; failed: 2; total: 6; seconds spent: 0.000078"
zbxdb.vserver15768.zbx sent: 1506; skipped: 0; total: 1506

Any ideas?

Thanks again for your help.  I feel that I am getting pretty close.

**Comment by ikzelf** [comment]
Your hostname should be MSSQLSERVER, as that is what is in hostname in the cfg file. The individual databases will be auto discovered. If you just restart the zbxdb process, it will run all discoveries at once and send data for all discoveries.
Data for the individual databases is accepted after they have been discovered. So after a while most data will be accepted and you will start seeing the entries in 'latest data'.
I might have made errors, causing some data keys to mismatch with the discovery keys but most data will be accepted if the keys have been created after the auto discovery. Most discoveries are done once an hour.
I hope this will work for you now. Since I am not that guy without errors, I hope you can help me getting this better. I already noted that testing on the existence of zabbix_sender might make life a little easier so thanks for that tip.

**Comment by rlfink** [comment]
Hi Ron-

Everything seems to be working great now.

I do have some configuration news for you.    I listed the hostname as the physical hostnames in the config files and created the physical hostname in Zabbix.   Even though both SQL Server instance names are MSSQLSERVER, I am now able to see both my non-production and production databases which have the same names but listed separately by host name.

For example:
Development host server:  vserver15768, instance MSSQLSERVER
Production host server:  vserver16062, instance MSSQLSERVER

In doing so, the zbxdb discovery found my “datahub” database listed under each server and is shown separately in Zabbix.  This is great news for me.

Now on to configure my MySQL servers.

Thanks again!

**Comment by ikzelf** [comment]
Hi Randy,
yes, zbxdb finds all databases attached to the instance, dynamically. What you can see in sql studio you could see in zabbix, using zbxdb.
So in the end the only problem was the missed installation of zabbix-sender. I will add a check for that so new users are sooner aware of the fact that it is needed.

Thanks for the feedback and feel free to add improvements by issuing PR's.
