### ISSUE TITLE
 zbxdb_sender.py and zbxdb_sender

### ISSUE THREAD

**Issue by kakoni** [ikzelf/zbxdb#27]
Hi.
Currently there is two scripts zbxdb_sender.py and zbxdb_sender to send logs to zabbix server.
They seem to do similar things, so perhaps zbxdb_sender bash script should be retired?

**Comment by ikzelf** [comment]
Yes, you are right, I could remove the bash script as the functionality is exactly the same as the python version is. If I remove it, it breaks the installations that still use the bash version. That's the reason to keep it. It would also force those users to install python, where they now might be doing without python installation at all.
On this point I am not sure what to do .... remove or keep it.

**Comment by ikzelf** [comment]
I moved the bash script to example_tools/
