### ISSUE TITLE
Undocumented binaries

### ISSUE THREAD

**Issue by kakoni** [ikzelf/zbxdb#28]
Currently it is bit unclear what these scripts are doing;

tnslsnr-ping.py
zbx_agent.sh
zbx_discover_lsnr.py
zbx_exaserver.sh
zbx_odaserver.sh

**Comment by ikzelf** [comment]
Thanks for the feedback.
They can be seen as examples of how you could use own scripting to integrate Oracle exadata and Oracle Database Appliance monitoring with zabbix. Maybe I should put them in some examples or tools folder, with some explanation with it?
