### ISSUE TITLE
What is difference between db_url and hostname in zbxdb.ms.cfg?

### ISSUE THREAD

**Issue by rlfink** [ikzelf/zbxdb#30]
Requesting a documentation enhancement describing the difference and correct usage of the zbxdb config lines db_url, server, and hostname.   

I currently set "db_url" to the local zabbix database, in my case a MySQL database named "zabbix" residing on localhost.
db_url = //localhost/zabbix

I have set "server" to the monitored database server name or IP.  Below is an example of an Azure SQL name.
server = tc3vmdevdb4.database.windows.net

I have set "hostname" to the Zabbix configured hostname used for matching Zabbix configuration to the ZBXDB generated database statistics.  
hostname = tc3vmdevdb4

While I am fairly certain that my usage of server and hostname are correct, I need to better understand db_url.   I do see some errors below which I am trying to better understand as some of my Azure databases do not have a physical host (I implemented pyodbc to connect to Azure SQL and managed instance databases).
WARNING:__main__:(1.311)connection error: [0] 42000 for zabbix_stat@//localhost/zabbix

**Comment by ikzelf** [comment]
Hi,
yes, I agree, the db_url is certainly in the case of mysql a bit misleading and confusing. For oracle it is used, for mysql more like a short form a connection for the log.
For mysql connection parameters you need to specify
server
username
password
db_name
server_port

like in the example I put in etc/zbxdb.mysql.cfg 
In this case db_url is more a form of nice printing of the details that are created from
"{usr}/{pwd}@{server},{server_port}/{db_name}"

**Comment by rlfink** [comment]
Thank you
