### ISSUE TITLE
the zbxdb_sender shell script in bin is missing

### ISSUE THREAD

**Issue by Scott-Hughes-Automic** [ikzelf/zbxdb#31]
**Describe the bug**

**To Reproduce**
1. cfg file  obfuscate entries like address, username and password
2. driver version
3. db version
4. monitoring platform
5.  failing SQL

**Expected behavior**

**logs**
If applicable, add logs to help explain your problem.

**monitoring platform:**
 - distribution, version
 - python version
 - driver version

**Additional context**

**Comment by ikzelf** [comment]
Hi,
you might consider using the python script instead. It has better logging and error handling.
If you still want the bash script, now it is in the extra_tools folder.

Groeten,
Ronald Rood

**Comment by Scott-Hughes-Automic** [comment]
OK thanks.  I am putting this in a container to monitor some production db availability.  I am almost done and don't want to switch senders right now.  My sed command to change the zabbix_sender config was failing.  I copied an old copy of the file over.  I'll look at the python file.
