### ISSUE TITLE
Install on Windows?

### ISSUE THREAD

**Issue by killmasta93** [ikzelf/zbxdb#32]
Hi,
I was reading the getting started guide https://github.com/ikzelf/zbxdb/blob/master/doc/getting_started.md
But it does not apply for windows as i need to try out on server 2012  with MSSQL 2008-2016
I was checking if there is a step by step guide in the READ me section but could not find it 

Thank you

**Comment by ikzelf** [comment]
I recommend running zbxdb in zabbix server and/or zabbix proxies. Most of them run Linux since AFAIK they are not supported on windows. Still, zbxdb should be able to run on windows. Just start with installing pyenv and python3. The rest should be similar to Linux.
