### ISSUE TITLE
Need ZabDash queries

### ISSUE THREAD

**Issue by rlfink** [ikzelf/zbxdb#33]
What are the SQL queries used to populate the ZabDash dashboard, ie Triggers by host - Top 10 and Triggers by Severity?   I am having trouble identifying why I have numbers displayed when I have no active issues. Also, from what script are these queries executed?  Thank you

**Comment by ikzelf** [comment]
The queries van be found in etc/zbxdb_checks/{db_engine}/primary.{version}.cfg
zbxdb.py uses the configfile to find them. After zbxdb.py connects to the instance it finds what version the instance has and loads the corresponding version file.

**Comment by rlfink** [comment]
Thanks so much for the quick reply.

**Comment by rlfink** [comment]
My mistake.  I am looking for the queries which read the Zabbix tables, not the database performance stats.

**Comment by rlfink** [comment]
I found what I needed.  It was in triggers_severity_tab.inc.php.
