### ISSUE TITLE
ASM cluster monitoring configuration

### ISSUE THREAD

**Issue by Largelos** [ikzelf/zbxdb#34]
Could you please describe how to properly monitor Oracle ASM instances in the cluster environment? 
ASM instances are not registered in the high availability SCAN listener, so I have to specify hostname to one of cluster's node in db_url parameter. Script in this case receives the status for all ASM instances in normal situation. But, if this host become unavailable, data will no longer be updated, even while another nodes instances still online. 
At the same time, I can’t add several cfg files and zabbix hosts, one for each node of the cluster, because in this case the metrics and triggers will be duplicated, and events will also cause doubles.
Is it possible to use some kind of failover mechanism for the database connection string, or is some other ASM monitoring logic supposed to be?

**Comment by ikzelf** [comment]
Easiest is to create a regular sqlnet connect string that describes all instances. This way it will connect the first available instance in the list.

Groeten,
Ronald Rood

**Comment by ikzelf** [comment]
One example I have without tnsnames.ora:
[zbxdb]
db_url = (DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=dm0201-vip)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dm0202-vip)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=+ASM)(SERVER=DEDICATED)))
username = cistats
role = sysdba
db_type = oracle
db_driver = cx_Oracle
instance_type = asm
hostname = dm02_ASM

**Comment by Largelos** [comment]
Thx, exactly that I wanted to hear about the ability to use not only ezconnect but also full tnsnames connection string :)
Great script, thank you.
