### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlparse'

### ISSUE THREAD

**Issue by doumhfr** [ikzelf/zbxdb#40]
Hi,

I have installed zbxdb using the getting started
but when I try to run it (zbxdb.py) I get this error 👍 

Traceback (most recent call last):
  File "./zbxdb/bin/zbxdb.py", line 36, in <module>
    import sqlparse
ModuleNotFoundError: No module named 'sqlparse'

but pip list give me : 
sqlparse (0.3.1)

(server is ubuntu 18.04)

thanks for your help

**Comment by ikzelf** [comment]
How did you install your python installation? Did you use pyenv?

**Comment by doumhfr** [comment]
exactly as in getting started

logged on account zbxdb : 

curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

pyenv install 3.6.5

git clone https://github.com/ikzelf/zbxdb.git

pip install -r zbxdb/requirements.txt

in my .pyenv folder I have 
pyenv/versions/3.6.5/

**Comment by ikzelf** [comment]
Did you also update your .bashrc or .bash_profile and reloaded that?
Did you set “pyenv global 3.6.5”?
What do you get from “type python” ?

**Comment by doumhfr** [comment]
no, sorry i'm new with python
i just have to use this command ? (pyenv global 3.6.5)

type python 
python is /usr/bin/python

I think it should be /home/zbxdb/.pyenv/versions/3.6.5/bin/python instead ?

**Comment by ikzelf** [comment]
Yes and you get that when you finish the pyenv installation :

‘then remove these three lines from .bashrc:

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
and finally, restart your shell:

$ exec $SHELL’

**Comment by doumhfr** [comment]
I don't have these lines in .bashrc

**Comment by ikzelf** [comment]
You need to add them manually. After that, logout, login again and check the result of ‘type python’ again.

**Comment by doumhfr** [comment]
oh ok you said then remove these three lines so I thank I need to verify I don't have these lines

**Comment by doumhfr** [comment]
ok it's better now I don't have the error

crontab exec : 
May 11 21:43:01 zabbix CRON[23083]: (zbxdb) CMD ($HOME/zbxdb/bin/zbxdb_starter > /dev/null 2>&1)
May 11 21:43:01 zabbix CRON[23084]: (zbxdb) CMD ($HOME/zbxdb/bin/zbxdb_sender > /dev/null 2>&1)

but seems to do nothing

logs are still 20 minutes old 
-rw-rw-r-- 1 zbxdb zbxdb  777 May 11 21:25 zbxdb.ORACLETST1.cfg.log
-rw-rw-r-- 1 zbxdb zbxdb    0 May 11 21:25 zbxdb.log
-rw-rw-r-- 1 zbxdb zbxdb 2559 May 11 21:25 zbxdb_starter.log

if I run manualy  $HOME/zbxdb/bin/zbxdb_starter it's working (I have a connection error but it's not zbxdb side)

**Comment by ikzelf** [comment]
The zbxdb*.log is updated once an hour. It should add to a file in zbxdb_out/ every minute.

zbx_sender moves the files to zbx_sender/in, processes them and zips them to the zbx_sender/archive/

**Comment by doumhfr** [comment]
arf ok. I have things in zbxdb_out

but nothing in zbx_sender 

zbxdb@zabbix:~/zbxdb_sender$ ls -lsa
total 8
4 drwxrwxr-x  2 zbxdb zbxdb 4096 May 11 17:01 .
4 drwxr-xr-x 11 zbxdb zbxdb 4096 May 11 23:04 ..

no subfolder.

I have to create them manually ?

**Comment by doumhfr** [comment]
maybe if I install zabbix-sender it's better 👎 
Sorry i'm tired

**Comment by doumhfr** [comment]
hum no not better after 

after a reboot the file in zbxdb_out doesn't update anymore...

**Comment by doumhfr** [comment]
zbxdb@zabbix:~/zbxdb/bin$ zbxdb.py -c /home/zbxdb/etc/zbxdb.ORACLETST1.cfg
Falling back to default logging config
WARNING:__main__:start python-3.6.5 zbxdb-2.07 pid=7282 Connecting ...

WARNING:__main__:zbxdb found db_type=oracle, driver cx_Oracle; checking for driver

CRITICAL:__main__:problem
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 829, in <module>
    main()
  File "/home/zbxdb/zbxdb/bin/zbxdb.py", line 315, in main
    " does not exist in the "+_config['checks_dir']+" directory")
ValueError: db_type oracle does not exist in the etc/zbxdb_checks directory

strange this error no ?

**Comment by doumhfr** [comment]
I think you have an error in the getting started documentation

add into the crontab:
* * * * * $HOME/zbxdb/bin/zbxdb_starter > /dev/null 2>&1
* * * * * $HOME/zbxdb/bin/zbxdb_sender > /dev/null 2>&1

$HOME/zbxdb/bin/zbxdb_sender doesn't exist
it's $HOME/zbxdb/bin/zbxdb_sender.py

**Comment by doumhfr** [comment]
2020-05-11 23:50:01,401___main___50_zbxdb_sender specify ZBXDB_OUT in the environment or as first argument of zbxdb_sender
Usage zbxdb_sender [ZBXDB_OUT]
   to collect zbxdb.py outputs from that directory to send to zabbix
   ZBXDB_OUT should point to the out_dir directory in the zbxdb.py config[s]
   using zbxdb_sender directory in /home/zbxdb for work space
   sending to ZABBIX_SERVER /home/zbxdb on ZABBIX_SERVER_PORT 127.0.0.1

i have this now in zbxdb_sender.log

**Comment by doumhfr** [comment]
ok sorry i missread the part regarding crontab

but this I don't understand in zbxdb_sender.log : 

2020-05-12 00:02:01,775___main___50_zbxdb_sender ZBXDB_OUT directory {/home/zbxdb/zbxdb_out} does not exist

zbxdb@zabbix:~$ cd /home/zbxdb/zbxdb_out
zbxdb@zabbix:~/zbxdb_out$

This folder exists

**Comment by ikzelf** [comment]
I saw that the getting started doc was a bit strange formatted that might have caused you missing steps. The step 'pyenv global 3.6.5' was completely missing. Thanks for pointing the out.

**Comment by doumhfr** [comment]
you're welcome ;)

do you have an idea for this ?
2020-05-12 00:02:01,775___main___50_zbxdb_sender ZBXDB_OUT directory {/home/zbxdb/zbxdb_out} does not exist

I'm have set this in crontab : 
* * * * * export ZBXDB_OUT={/home/zbxdb/zbxdb_out};$HOME/zbxdb/bin/zbxdb_sender.py > /dev/null 2>&1

I don't understand

**Comment by ikzelf** [comment]
change that to:
* * * * * export ZBXDB_OUT=${HOME}/zbxdb_out;$HOME/zbxdb/bin/zbxdb_sender.py > /dev/null 2>&1

**Comment by doumhfr** [comment]
It's better 👍 

2020-05-12 10:17:01,371___main___30_ZABBIX_SERVERS 127.0.0.1 ZABBIX_SERVER_PORTS 10051
2020-05-12 10:17:01,371___main___30_Logging in /home/zbxdb/log/zbxdb_sender.log
2020-05-12 10:17:01,389___main___30_2020-05-12-1017 processing zbxdb.ORACLETST1.zbx
2020-05-12 10:17:01,402___main___30_removed lock /home/zbxdb/zbxdb_sender/zbxdb_sender.lock

but I have nothing in the host in zabbix, all items from the template zbxdb stay with no data

**Comment by ikzelf** [comment]
can you show a few lines from the file in zbxdb_out/ ?
It should list the exact hostname.
Can you kill the zbxdb.py process and have it restarted by zbxdb_starter.py ? During the first run it does a few extra things ....

**Comment by doumhfr** [comment]
ORACLETST1 "zbxdb[connect,status]" 1589283272 12154
ORACLETST1 "zbxdb[uptime]" 1589283272 31
ORACLETST1 "zbxdb[connect,status]" 1589283284 12154
ORACLETST1 "zbxdb[uptime]" 1589283284 43
ORACLETST1 "zbxdb[connect,status]" 1589283295 12154
ORACLETST1 EV "zbxdb[uptime]" 1589283295 54

j'ai des erreurs de connexion dans le zbxdb.ORACLETST1.cfg.log
 ORA-12154: TNS:could not resolve the connect identifier specified for user@ORACLETST1

j'ai essayé plein de truc au niveau du db_url mais en vain

pourtant sqlplus se connecte bien

sqlplus -l user@ORACLETST1

SQL*Plus: Release 19.0.0.0.0 - Production on Tue May 12 13:37:59 2020
Version 19.5.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Mon May 11 2020 22:44:18 +02:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

peut etre des variables qui manquent a python pour connaitre les chemins du tnsname ou des trucs du genre ?

**Comment by ikzelf** [comment]
I never used tnsnames.ora for this. Instead I used ezconnect string like //host[:port]/service
I did nothing to prevent the use of regular sqlnet settings .... Did you define TNS_ADMIN?
[https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html)

**Comment by doumhfr** [comment]
better now; I had a typo error....

the ezconnect string works when you use sid ? (I don't know well oracle)

ORACLETST1 "zbxdb[uptime]" 1589285042 301
ORACLETST1 "zbxdb[opentime]" 1589285042 160
ORACLETST1 "blocked[count]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,blocked,status]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,blocked,ela]" 1589285042 0.0010216769987891894
ORACLETST1 "zbxdb[query,checks_01m,blocked,fetch]" 1589285042 0.00010480499986442737
ORACLETST1 "db[TST,openstatus]" 1589285042 3
ORACLETST1 "zbxdb[query,checks_01m,db.openmode,status]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,db.openmode,ela]" 1589285042 0.0021113249986228766
ORACLETST1 "zbxdb[query,checks_01m,db.openmode,fetch]" 1589285042 0.0001726949994917959
ORACLETST1 "inst[TST,uptime]" 1589285042 1306321
ORACLETST1 "zbxdb[query,checks_01m,inst.uptime,status]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,inst.uptime,ela]" 1589285042 0.0007348620001721429
ORACLETST1 "zbxdb[query,checks_01m,inst.uptime,fetch]" 1589285042 0.00016487900029460434
ORACLETST1 "db[current_scn]" 1589285042 24462810
ORACLETST1 "db[delta_scn]" 1589285042 24462810
ORACLETST1 "zbxdb[query,checks_01m,scn,status]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,scn,ela]" 1589285042 0.004375317001176882
ORACLETST1 "zbxdb[query,checks_01m,scn,fetch]" 1589285042 0.0005874849994143005
ORACLETST1 "inst[TST,user calls]" 1589285042 4086240
ORACLETST1 "inst[TST,DB time]" 1589285042 1322364
ORACLETST1 "inst[TST,execute count]" 1589285042 53229680
ORACLETST1 "inst[TST,processes]" 1589285042 99
ORACLETST1 "inst[TST,sessions]" 1589285042 72
ORACLETST1 "zbxdb[query,checks_01m,sysstat,status]" 1589285042 0
ORACLETST1 "zbxdb[query,checks_01m,sysstat,ela]" 1589285042 0.013130056999216322
ORACLETST1 "zbxdb[query,checks_01m,sysstat,fetch]" 1589285042 0.011220675998629304
ORACLETST1 "zbxdb[query,checks_01m,,ela]" 1589285042 0.02278176700019685
ORACLETST1 "zbxdb[query,,,ela]" 1589285042 0.024038083000050392
ORACLETST1 "zbxdb[cpu,user]" 1589285042 0.5925199999999999
ORACLETST1 "zbxdb[cpu,sys]" 1589285042 0.102559
ORACLETST1 "zbxdb[mem,maxrss]" 1589285042 39696
ORACLETST1 "zbxdb[connect,status]" 1589285042 0

but still nothing in zabbix  :(

**Comment by ikzelf** [comment]
The key "zbxdb[connect,status]" should get data, if all is OK.
Is your hostname in zabbix "ORACLETST1" (case sensitive)?
Did you link the zbxdb template?
What is in the server and proxy log?
If your host is behind a zabbix proxy, refresh the configuration cache.

**Comment by doumhfr** [comment]
ok the server log has the answer :D 

 2317:20200512:142501.652 connection of type "unencrypted" is not allowed for host "ORACLETST1"

zabbix_sender doesn't use the good conf. I thank it use the agent configuration?

**Comment by ikzelf** [comment]
[https://www.zabbix.com/documentation/4.0/manpages/zabbix_sender](https://www.zabbix.com/documentation/4.0/manpages/zabbix_sender)

I could change zbxdb_sender.py to pass an optional -c...
as a test, change:
147     for server, port in zip(s, p):
148         process = subprocess.Popen(["zabbix_sender -z {} -p {} -T -i {} -vv"
149                                     .format(
150                                         server,
151                                         port,
152                                         os.path.join(TMPIN, f))],

to:
147     for server, port in zip(s, p):
148         process = subprocess.Popen(["zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -T -i {} -vv"
149                                     .format(
152                                         os.path.join(TMPIN, f))],

(in zbxdb/bin/zbxdb_sender.py)

**Comment by doumhfr** [comment]
it"s working !!!

thank you a thousand times for all your help! :)
