### ISSUE TITLE
Send data to Zabbix server but don't delivery

### ISSUE THREAD

**Issue by absz1980** [ikzelf/zbxdb#41]
**Describe the bug**
I configure simple Oracle DB but nodata in Zabbix server. Data collect in zbxora_out/zbxdb.vs-tst00-idb01.zbx but don't delivery to Zabbix Server.

**To Reproduce**
1. cfg file  obfuscate entries like address, username and password
cat zbxdb.vs-tst00-idb01.cfg
[zbxdb]
db_url = //vs-tst00-idb01/B2BSKTST
username = cistats
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxora_out
hostname = vs-tst00-idb01
checks_dir = etc/zbxdb_checks
site_checks = primary.11
password_enc = *******

2. driver version
Oracle Instant Client 19.3

3. db version
11.2.0.4

4. monitoring platform
Zabbix Server 4.4.7

5.  failing SQL
No SQL

**Expected behavior**

**logs**
********************************************************************************************************

cat ../log/zbxdb_starter.log
Tue Jun 16 15:18:01 MSK 2020 Starting etc/zbxdb.vs-tst00-idb01.cfg
*********************************************************************************************************
 cat ../log/zbxdb.vs-tst00-idb01.cfg.log
2020-06-16 15:18:01,864___main___30_start python-3.6.5 zbxdb-2.07 pid=126139 Connecting ...

2020-06-16 15:18:01,865___main___30_zbxdb found db_type=oracle, driver cx_Oracle; checking for driver

2020-06-16 15:18:04,936___main___50_file etc/zbxdb_checks/oracle/primary.11.cfg has parsing errors ->(13)

2020-06-16 15:18:04,941___main___50_file etc/zbxdb_checks/oracle/primary.11.cfg has parsing errors ->(13)

****************************************************************************************************
crontab -l
* * * * * $HOME/zbxdb/bin/zbxdb_starter > /dev/null 2 >&1
* * * * * $HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out > /dev/null 2 >&1

****************************************************************************************************

**monitoring platform:**
CentOS Linux release 7.7.1908 (Core)
python 3.6.5
 

**Additional context**

**Comment by ikzelf** [comment]
Are there any problems in the zbxdb_sender.log ?

btw: site_checks = primary.11
zbxdb will find out which checks file it needs and will automatically go for primary.11, if your database appears to be a v11 and has the role of a primary database/ The site_checks parameter is more meant to give you a place to add application/site specific checks.

**Comment by absz1980** [comment]
Hello, Ikzelf, 
thank you.

>Are there any problems in the zbxdb_sender.log?
I haven`t zbxdb_sender.log in log location.
[zbxdb@msk01-monapp02 log]$ ls -l
total 8
-rw-rw-r-- 1 zbxdb zbxdb   0 Jun 16 15:18 zbxdb.log
-rw-rw-r-- 1 zbxdb zbxdb 134 Jun 16 16:30 zbxdb_starter.log
-rw-rw-r-- 1 zbxdb zbxdb 819 Jun 16 16:30 zbxdb.vs-tst00-idb01.cfg.log

I change out_dir location and restart jobs but messages are not delivered yet

cat zbxdb.vs-tst00-idb01.cfg
[zbxdb]
db_url = //vs-tst00-idb01.uralsibins.ru/B2BSKTST
username = cistats
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
#hostname = vs-tst00-idb01
checks_dir = etc/zbxdb_checks
site_checks = primary.11
password_enc =

**Comment by ikzelf** [comment]
Remove this line with "site_checks = primary.11"

**Comment by absz1980** [comment]
I remove "site_checks = primary.11" and restart.
Messages  are not delivered yet.

 cat zbxdb.vs-tst00-idb01.cfg
[zbxdb]
db_url = //vs-tst00-idb01.uralsibins.ru/B2BSKTST
username = cistats
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
checks_dir = etc/zbxdb_checks
password_enc = 


cat zbxdb.vs-tst00-idb01.cfg.log
2020-06-16 17:02:01,597___main___30_start python-3.6.5 zbxdb-2.07 pid=32041 Connecting ...

2020-06-16 17:02:01,597___main___30_zbxdb found db_type=oracle, driver cx_Oracle; checking for driver

2020-06-16 17:02:04,666___main___50_file etc/zbxdb_checks/oracle/primary.11.cfg has parsing errors ->(13)

[zbxdb@msk01-monapp02 log]$

**Comment by ikzelf** [comment]
I hope I just removed the parse error from the primary.11.cfg.
You could pull that from GitHub.
Normally a file should be written in zbxdb_out/ like zbxdb.vs-tst00-idb01.zbx
This should be picked up once a minute and moved to zbxdb_sender/archive/ after processing and to zbxdb_sender/in/ during processing by zbxdb_sender.

**Comment by absz1980** [comment]
I waited 10min. I didn`t see files in zbxdb_sender/in archive.
And no data in Zabbix Server.

cat zbxdb.vs-tst00-idb01.cfg.log
2020-06-16 17:25:01,980___main___30_start python-3.6.5 zbxdb-2.07 pid=41090 Connecting ...

2020-06-16 17:25:01,980___main___30_zbxdb found db_type=oracle, driver cx_Oracle; checking for driver

**Comment by ikzelf** [comment]
Did you also copy logging_sender.json to your etc/ folder?
This should define the logfile for the sender.
Good to see that the parsing error is gone now.

You might want to start zbxdb.py with a higher verbosity. Normally when everything is OK, it logs one line every hour.

If you find your zbxdb.vs-tst00-idb01.zbx file, check the contents. It should have hostname key timestamp value, separated by a space in it. The hostname should be taken from your hostname = vs-tst00-idb01

**Comment by absz1980** [comment]
Hello!

The logging_sender.json file did in /etc folder

[zbxdb@msk01-monapp02 etc]$ pwd
/home/zbxdb/etc
[zbxdb@msk01-monapp02 etc]$ cat logging_sender.json
{
    "version": 1,
                "_comment": "  copy this file as logging.json in etc/",
    "disable_existing_loggers": false,
    "formatters": {
        "simple": {
            "format": "%(asctime)s_%(name)s_%(levelno)s_%(message)s"
        },
                                "onlyTime":{
            "format": "%(asctime)s_%(name)s %(message)s"
                                }
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "onlyTime",
            "stream": "ext://sys.stdout"
        },

        "file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "formatter": "simple",
            "filename": "log/zbxdb_sender.log",
            "maxBytes": 10485760,
            "backupCount": 4,
            "encoding": "utf8"
        }
    },

    "root": {
        "level": "WARNING",
        "handlers": ["console", "file_handler"]
    }
}
[zbxdb@msk01-monapp02 etc]$

The file  zbxdb.vs-tst00-idb01.zbx is filling permanently but doesn`t send it to Zabbix.
How can troubleshoot this issue?

**Comment by ikzelf** [comment]
I think something is missing in your environment. When setting this up, first test zbxdb_sender.py manually to see where it complains about. If that works, automate it using the crontab.

**Comment by absz1980** [comment]
Hello!

I have not to file zbxdb_sender, only file zbxdb_sender.py and dir $HOME/zbxdb/bin  exclude PATH


[zbxdb@msk01-monapp02 ~]$ crontab -l
* * * * * $HOME/zbxdb/bin/zbxdb_starter > /dev/null 2 >&1
#* * * * * $HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out > /dev/null 2 >&1

[zbxdb@msk01-monapp02 ~]$ $HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out
2020-06-17 13:43:55,590___main__ Logging in /home/zbxdb/log/zbxdb_sender.log
2020-06-17 13:43:55,592___main__ Namespace(cfile='/etc/zabbix/zabbix_agentd.conf', verbosity=0, zbxdb_out='zbxdb_out')
2020-06-17 13:43:55,592___main__ zbxdb_sender needs zabbix_sender in PATH
[zbxdb@msk01-monapp02 ~]$ env | grep PATH
PATH=/home/zbxdb/.pyenv/plugins/pyenv-virtualenv/shims:/home/zbxdb/.pyenv/shims:/home/zbxdb/.pyenv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/zbxdb/.local/bin:/home/zbxdb/bin:/home/zbxdb/zbxdb/bin
[zbxdb@msk01-monapp02 ~]$

**Comment by ikzelf** [comment]
OK, just install zabbix-sender from yum/apt or whatever you use and it will work.
(I changed the getting started doc to include output from the crontab lines. That would have it made a bit easier to find this.

**Comment by absz1980** [comment]
Hello, Ronald!
I install zabbix-sender

[zbxdb@msk01-monapp02 log]$ $HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out
Falling back to default logging config
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/zbxdb_sender.py", line 59, in <module>
    LOGGER.warning("Logging in %s", LOGGER.root.handlers[1].baseFilename)
IndexError: list index out of range
[zbxdb@msk01-monapp02 log]$

**Comment by absz1980** [comment]
Hello, Ronald!

Я remove files in zbxdb_out and it`s work!!!
But  
* * * * * $HOME/zbxdb/bin/zbxdb_starter > log/zbxdb_starter.cron 2 > &1
* * * * * $HOME/zbxdb/bin/zbxdb_sender -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out > log/zbxdb_sender.cron 2 > &1

probably incorrect. 
  "2 > &1" -> "2>&1" - with space
 "zbxdb_sender" ->  zbxdb_sender.py without "py"
without PATH

My work environment

PATH=/home/zbxdb/.pyenv/plugins/pyenv-virtualenv/shims:/home/zbxdb/.pyenv/shims:/home/zbxdb/.pyenv/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/zbxdb/.local/bin:/home/zbxdb/bin:/home/zbxdb/zbxdb/bin
* * * * * $HOME/zbxdb/bin/zbxdb_starter > $HOME/log/zbxdb_starter.cron 2>&1
* * * * * $HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out > $HOME/log/zbxdb_sender.cron 2>&1

**Comment by ikzelf** [comment]
glad you could fix your issues. 
And yes, documentation improves every time ....

Thanks.

**Comment by absz1980** [comment]
One question.
During installation, I've been facing the issue of dependencies.
rpm - postgresql12, postgresql12-devel.rpm \
@development zlib-devel bzip2 bzip2-devel readline-devel sqlite \
sqlite-devel openssl-devel xz xz-devel libffi-devel findutils \

and after Oracle Client
https://oracle.github.io/odpi/doc/installation.html#oracle-instant-client-rpm
These dependencies did not resolve during run "pip install -r zbxdb/requirements.txt"

Why didn`t I see in documentation?

**Comment by ikzelf** [comment]
Do you mean that you expected that the oracle instant client would be installed during the pip install from the requirements file?
That’s not the case. I could add that to the docu, if that would help.

Is that what you mean?

**Comment by absz1980** [comment]
I mean that all dependencies should add to docu. Because It avoids issue.
Thank you.

**Comment by ikzelf** [comment]
Ah yes, you are right.
Do you have time to add that?
I will be more than happy to accept your contribution.

**Comment by absz1980** [comment]
Ok. I know git bad.
If you instruct me I will add to docu

**Comment by ikzelf** [comment]
easiest is to first clone zbxdb into your own GitHub account. Make the changes there and create a Pull Request.
[https://opensource.com/article/19/7/create-pull-request-github](https://opensource.com/article/19/7/create-pull-request-github)

**Comment by absz1980** [comment]
I write, and you decide. My deadline is on fire. I don't have time to study the request.

my article

******************************************************************************************
Dependencies

For Enterprise Linux

yum install @development zlib-devel bzip2 bzip2-devel readline-devel sqlite \
sqlite-devel openssl-devel xz xz-devel libffi-devel findutils

Need to install Postgresql client

Follow https://yum.postgresql.org/repopackages.php#pg12 and choose Repo required OS version
yum install postgresql12 postgresql12-devel

On-demand 
Need Install latest Oracle Instant Client
https://oracle.github.io/odpi/doc/installation.html#oracle-instant-client-rpm
********************************************************************************************
