### ISSUE TITLE
SQL Error in etc/zbxdb_checks/oracle/primary.11.cfg

### ISSUE THREAD

**Issue by absz1980** [ikzelf/zbxdb#42]
**Describe the bug**
SQL Error in etc/zbxdb_checks/oracle/primary.11.cfg

**To Reproduce**
1. cfg file  obfuscate entries like address, username and password
etc/zbxdb_checks/oracle/primary.11.cfg
2. driver version
3. db version
11.2.0.4
4. monitoring platform
Zabbix 4.4.7
5.  failing SQL
rman.lld: select distinct(object_type) "{#OBJ_TYPE}" from v$rman_status where operation like 'BACKUP%'
          union all
          select 'usermanaged' from v$backup where change  # > 0 and file# = 1

It is extra space in  "change  #"  
The "change#" is right.

**Comment by absz1980** [comment]
It`s my problem.

**Comment by ikzelf** [comment]
no, my editor happens to do some funny things with this kind of names and converts them to comments. :-(

**Comment by absz1980** [comment]
Is this ussue not commit to master?

**Comment by ikzelf** [comment]
I just did
