### ISSUE TITLE
Many Oracle instance on one host

### ISSUE THREAD

**Issue by absz1980** [ikzelf/zbxdb#43]
Hello!

How can I configure a host with two oracle instance?

**Comment by ikzelf** [comment]
What do you mean?
zbxdb supports RAC so in case of RAC you just configure a connection to the scan listener.

If you have multiple databases on one machine, create a configuration file and a zabbix_host for each database. You will have a separate zabbix_host for every oracle database, or in case you use multi tenant databases, just one for the root container.
