### ISSUE TITLE
Monitoring ODA and ACFS

### ISSUE THREAD

**Issue by ccbezerra** [ikzelf/zbxdb#48]
Hello,
I have an ODA  (Oracle Database Appliance), which uses ACFS.

Would it be possible to create some monitoring for ACFS and ODA ?

**Comment by ikzelf** [comment]
Yes, acfs is already implemented. Maybe not for your specific version but take a look at the asm and apx files.
I did some minimal scripting to fetch some hardware stats. Mostly like all is ok or something is not. Intention was to keep this simple and attract attention to the device.

**Comment by ikzelf** [comment]
I guess this is working as expected.
