### ISSUE TITLE
Monitoring alert log zabbix version  less than 4.4 

### ISSUE THREAD

**Issue by absz1980** [ikzelf/zbxdb#52]
Hello,

Can I monitor alert log in zabbix version less than 4.4?
I try to import https://raw.githubusercontent.com/ikzelf/zbxdb/master/zbx_template_alertlog.xml and
Import failed
Invalid tag "/zabbix_export/version": unsupported version number.

![image](https://user-images.githubusercontent.com/11979643/93388979-2b9fa900-f874-11ea-9dfb-f8ce82ad2c89.png)

**Comment by ikzelf** [comment]
What you can try is edit the version line in the xml and see what error follows in de import. It should work in older versions, I just forgot to export it. Once you got this imported, could you send me the exported file so I can add it to the repository?

**Comment by absz1980** [comment]
Hi, Ronald

I  have changed version to 4.0. and error arise "Import failed
Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "snmp_community" is missing."

**Comment by absz1980** [comment]
![image](https://user-images.githubusercontent.com/11979643/93458346-dbaef980-f8e8-11ea-84fa-c6bef169690a.png)
![image](https://user-images.githubusercontent.com/11979643/93458382-e6698e80-f8e8-11ea-97b4-b674623d6f80.png)

**Comment by ikzelf** [comment]
In v4 every item, item prototype and discovery rule should contain this tag: "<snmp_community/>"
Look for an example in zbxdb_template_v4.xml
You can just add them to the xml and retry.

**Comment by absz1980** [comment]
I correct for version 4.0 but Incorrect trigger expression. Check expression part starting from ..
for all triggers

![image](https://user-images.githubusercontent.com/11979643/93474927-b29a6300-f900-11ea-8b1d-7edc217cbdf0.png)

**Comment by absz1980** [comment]
No, file zbx_template_alertlog_v4.xml.txt didn`t import.
![image](https://user-images.githubusercontent.com/11979643/93485272-93550300-f90b-11ea-9eee-49846fd20769.png)

I add many black parameters. And change my parameter value 
<type>ZABBIX_ACTIVE</type> <request_method>POST</request_method> to number value ...
I have done.,
And finally expression invalid.

**Comment by ikzelf** [comment]
[zbx_template_alertlog_v4.xml.txt](https://github.com/ikzelf/zbxdb/files/5240134/zbx_template_alertlog_v4.xml.txt)
I added the snmp_oid lines

**Comment by absz1980** [comment]
Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "status" is missing.
It`s more then 40 black parameters in every level and different xml structure. I was adding and restucture it.
Now it`s incorrect trigger expression. I think that ver 4.0 and 4.4 is incompatible.
 
Example
 <trigger_prototype>
                                    <expression>{iregexp(&quot;ORA-0*403(0|1|2|3|5|6):&quot;,2h)}=1</expression>
                                    <name>{#INSTANCE_NAME}[alertlog] allocate pga/shared</name>
                                    <priority>AVERAGE</priority>
                                    <description>memory problems shared pool or pga</description>
									<recovery_mode>0</recovery_mode>
                                    <recovery_expression/>
									<correlation_mode>0</correlation_mode>
									<correlation_tag/>
									<url/>
									<status>0</status>
									<type>0</type>
									<manual_close>0</manual_close>
									<dependencies/>
									<tags/>
                                </trigger_prototype>

**Comment by ikzelf** [comment]
Now the status tag is missing. The editing you did, is nice but I think you are missing some encoded characters.

**Comment by absz1980** [comment]
I upgraded to  4.4 and import template was success.
I have Oracle DB on Windows.
How do I run zbx_alertlog.py -o /etc/oratab -s <Zabbix server> -p 10051 -H 1 -k oracle.alertlog.lld on Windows hosts?
Can I configure items and trigger manually without zbx_alertlog.py?

**Comment by ikzelf** [comment]
ah, that's better.
I have no windows but it should work like: zbx_alertlog.py -s your_zabbix_server_or_proxy -p 10051 -H your_database_server -k oracle.alertlog.lld 

and yes, you can - of course - make it all manually. If you have python on your host it could work.

**Comment by absz1980** [comment]
Thank very match. I have done it.

I found the error in Template. type>ZABBIX_ACTIVE</type> but wok with Agent trapper. You told me the issue earlier.

 <discovery_rules>
                <discovery_rule>
                    <name>oracle.alertlog.lld</name>
                    <type>ZABBIX_ACTIVE</type>
                    <key>oracle.alertlog.lld</key>
                    <delay>20m</delay>
                    <lifetime>2w</lifetime>

**Comment by ikzelf** [comment]
Glad that you got it all working now.
