### ISSUE TITLE
ASM 10g

### ISSUE THREAD

**Issue by ddmo** [ikzelf/zbxdb#56]
Hi, I've adapt a cfg file to work with ASM on 10g.
I put the file etc/zbxdb_checks/oracle/asm.10.cfg

And now? How to add this configuration to the zbxdb software?
Thanks

**Comment by ikzelf** [comment]
Hi, nice.
Easiest is to clone zbxdb on GitHub, add your changes to your clone and create a pull request, that I will happily accept. Doing so you also get the credits for that. I assume you started with a copy of the v11 file. Did you need any changes?

**Comment by ikzelf** [comment]
Just in case your question was more about when zbxdb.py would select your asm.10.cfg:
1) zbxdb.py connects to your installation with the credentials you specified.
2) zbxdb.py will detect the instance type and version
3) based n the instance_type and version it will construct the name of the checks file -> {instance_type}.{version}.cfg

**Comment by ikzelf** [comment]
Do you need more help with this?

**Comment by ddmo** [comment]
Hi, I've problem with collecting data again... Then I'll try to configure ASM as you wrote.
Thanks!

**Comment by ddmo** [comment]
Ok, I've resolved the trouble. 
For ASM, if I understand I need to set an additional config file for ASM, like this:

```
[zbxdb]
db_url = (DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=dm0201-vip)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dm0202-vip)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=+ASM)(SERVER=DEDICATED)))
username = cistats
role = sysdba
db_type = oracle
db_driver = cx_Oracle
instance_type = asm
hostname = dm02_ASM

```

So, it's enough add a zbxdb.asm.cfg file in /etc directory and a proper asm.10.cfg file in etc/zbxdb_checks/oracle directory?
Thanks

**Comment by ikzelf** [comment]
yes, that is the idea. This way, if your ASM disks run out of space, the ASM host reports the problem and not every database using it. A bit like a nfs server and the nfs clients.

**Comment by ddmo** [comment]
Resolved putting query on primary config file
