### ISSUE TITLE
unable to csv-to-lld.py

### ISSUE THREAD

**Issue by rmdolezal** [ikzelf/zbxdb#57]
I have installed the template zbxdb_tnslsnr a now I try to send the listners def via csv-to-lld.py
But the result is allways the same:

doesn`t matter if runned from proxy or zbx server

 bin]#  ./csv-to-lld.py -v -c lsnr.csv -z dbhost -l oratns.lld
Namespace(configfile='lsnr.csv', lld_key='oratns.lld', port='10051', server='localhost', verbosity=1, zabbix_host='dbhost')
Writing to csv-to-lld.lld
zabbix_sender [100452]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 1; total: 1; seconds spent: 0.000023"}]
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000023"
sent: 1; skipped: 0; total: 1

[root@proxy-test-final bin]# cat lsnr.csv
{DNSNAME}:{PORT}
dbhost:1521

[root@proxy-test-final bin]# more csv-to-lld.lld
"dbhost" "oratns.lld" {"data":[{"{#DNSNAME}:{#PORT}": "dbhost:1521"}]}

I`m out of ideas.

Regards

Marek

**Comment by ikzelf** [comment]
did you get csv-to-lld from [https://github.com/ikzelf/csv-to-lld](url)?
When I use that:
```
$>cat lsnr.csv
{DNSNAME};{PORT}
orahost1;1521
orahost2;1521
client ronr@ronrmb03:~/Documents/git/csv-to-lld
$>bin/csv-to-lld.py -c lsnr.csv -z hostinzabbix -v
Namespace(configfile='lsnr.csv', lld_key='oradb.lld', port='10051', server='localhost', verbosity=1, zabbix_host='hostinzabbix')
Writing to csv-to-lld.lld
zabbix_sender [30433]: DEBUG: send value error: cannot connect to [[localhost]:10051]: [61] Connection refused
Sending failed.
client ronr@ronrmb03:~/Documents/git/csv-to-lld
$>cat csv-to-lld.lld
"hostinzabbix" "oradb.lld" {"data":[{"{#DNSNAME}": "orahost1", "{#PORT}": "1521"}, {"{#DNSNAME}": "orahost2", "{#PORT}": "1521"}]}
```

In your output there seem to be an issue regarding quotes.
And I currently have no local zabbix running so of course there is an error trying to send but the lld file seems to be fine.
hostinzabbix should be a host defined in zabbix and oradb.lld should be a discovery key from that hostinzabbix.

**Comment by rmdolezal** [comment]
Hi ronald,

Tryed with the same inputs as you:

[root@proxy-test-final bin]# cat lsnr.csv
{DNSNAME};{PORT}
orahost1;1521
orahost2;1521
[root@proxy-test-final bin]# ./csv-to-lld.py -c lsnr.csv -z hostinzabbix -v
Namespace(configfile='lsnr.csv', lld_key='oradb.lld', port='10051', server='localhost', verbosity=1, zabbix_host='hostinzabbix')
Writing to csv-to-lld.lld
zabbix_sender [27244]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 1; total: 1; seconds spent: 0.000026"}]
info from server: "processed: 0; failed: 1; total: 1; seconds spent: 0.000026"
sent: 1; skipped: 0; total: 1
[root@proxy-test-final bin]# cat csv-to-lld.lld
"hostinzabbix" "oradb.lld" {"data":[{"{#PORT}": "1521", "{#DNSNAME}": "orahost1"}, {"{#PORT}": "1521", "{#DNSNAME}": "orahost2"}]}


https://github.com/ikzelf/csv-to-lld.git
root@proxy-test-final bin]# ls -l csv-to-lld.py
-rwxr-xr-x 1 zbxdb zbxdb 3432 Oct 29  2019 csv-to-lld.py


Regards

marek

**Comment by ikzelf** [comment]
Hi Marek,

does the host "hostinzabbix" exist in zabbix and does it have the "oradb.lld" discovery key?

**Comment by ikzelf** [comment]
Hi Marek,

have you been able to solve this mystery?

**Comment by rmdolezal** [comment]
Hi Ronald,
Yes, it`s working now. The mystery was my mistake in hostname – at one character with upper case ☹.
So everything looks ok now.

Thank  you for you support.

Regards

Marek

**Comment by ikzelf** [comment]
Hi Marek,

I am glad you resolved this yourself. I will close this issue.
have a nice weekend,
Ronald.

**Comment by rmdolezal** [comment]
Hi Ronald,
Have a nice weekend too.

Marek
