### ISSUE TITLE
send data to Zabbix server

### ISSUE THREAD

**Issue by starlessboi** [ikzelf/zbxdb#6]
as far as I know mechanism to send collected data to Zabbix server is zbxdb_sender, what process is invoking sender to send data to zabbix?
when data is sent to database?
I can not find any data in my zabbix server from my monitored database
Thanks

**Comment by ikzelf** [comment]
put zbxdb_sender in the crontab, every minute.
It needs the zbxout directory name as argument

**Comment by starlessboi** [comment]
Thanks
it works for me

**Comment by ikzelf** [comment]
Glad I could help. Maybe you could write a simple blogpost about your findings and solutions?

Groeten,
Ronald Rood
