### ISSUE TITLE
Problem with zbxdb_sender.py

### ISSUE THREAD

**Issue by mhenninghaus77** [ikzelf/zbxdb#60]
Hello, couldn't start zbxdb_sender.py, i get this error message:
Falling back to default logging config Traceback (most recent call last): File "zbxdb_sender.py", line 59, in <module> LOGGER.warning("Logging in %s", LOGGER.root.handlers[1].baseFilename) IndexError: list index out of range

**Comment by ikzelf** [comment]
Hi,

did you copy logging_sender.json to your etc/ directory?

**Comment by mhenninghaus77** [comment]
Yes:

/home/adminteam/oracle/zbxdb/etc
adminteam@il06:etc > ls -la
total 40
drwxrwxr-x  4 adminteam users 4096 Dec 17 07:43 .
drwxrwxr-x 11 adminteam users 4096 Dec 16 12:33 ..
-rw-rw-r--  1 adminteam users  944 Dec 16 11:23 logging.json
-rw-rw-r--  1 adminteam users  940 Dec 16 11:23 logging_sender.json
drwxrwxr-x  2 adminteam users 4096 Dec 16 13:33 other
-rw-rw-r--  1 adminteam users  303 Dec 16 11:23 zbx_discover_oradbs.cfg
-rw-rw-r--  1 adminteam users  337 Dec 17 07:13 zbxdb.dev12a.cfg
-rw-rw-r--  1 adminteam users  337 Dec 17 07:42 zbxdb.dev12b.cfg
-rw-rw-r--  1 adminteam users  337 Dec 17 07:43 zbxdb.dev12c.cfg
drwxrwxr-x  8 adminteam users 4096 Dec 16 11:23 zbxdb_checks
adminteam@il06:etc >

**Comment by mhenninghaus77** [comment]
My cron:

*/15 * * * * . $HOME/.bash_profile;$HOME/oracle/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z zbxdb_out >log/zbxdb_sender.cron 2>&1

**Comment by ikzelf** [comment]
As far as I can see, 
you have /home/adminteam/oracle/zbxdb/etc/
and $HOME/oracle/

zbxdb_sender.py expects the json file in **$HOME/etc/**  is this what you have, or to you have the json files in $HOME/oracle/zbxdb/etc/

**Comment by mhenninghaus77** [comment]
i have it in $HOME/oracle/zbxdb/etc/ but i put it in $HOME/etc
but this doesn't work

**Comment by ikzelf** [comment]
The log entry: "Falling back to default logging config" means that zbxdb_sender.py is not able to find logging_sender.json in etc/logging_sender.json

Could you add to the .bash_profile: "export LOG_CFG_SENDER=$HOME/etc/logging_sender.json"

**Comment by mhenninghaus77** [comment]
i did but it doesn't work

**Comment by ikzelf** [comment]
Can you show me the results of 
`echo $LOG_CFG_SENDER`
`ls -l $LOG_CFG_SENDER`
`cat $LOG_CFG_SENDER`
`$HOME/oracle/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd.conf -z `

**Comment by mhenninghaus77** [comment]
hi, its working now, many thanks

**Comment by ikzelf** [comment]
I am glad it is all working now. Did you find out what was the issue (and solution)?
