### ISSUE TITLE
Can I get it to work with AWS RDS?

### ISSUE THREAD

**Issue by manoj-alwani** [ikzelf/zbxdb#62]
I followed the setup of zbxdb and can see data in $HOME/zbxdb_out and $HOME/zbxdb_sender/archive so connectivity to AWS RDS part is working.

I can see this error occasionally getting logged under $HOME/log/zbxdb_sender.log

2020-12-23 11:19:03,182___main___30_Logging in /home/zabbix/log/zbxdb_sender.log
2020-12-23 11:19:03,184___main___30_Namespace(cfile='/etc/zabbix/zabbix_agentd.conf', verbosity=0, zbxdb_out='zbxdb_out')
2020-12-23 11:19:03,184___main___30_Using /etc/zabbix/zabbix_agentd.conf
2020-12-23 11:19:03,184___main___30_2020-12-23-1119 processing zbxdb.zbxoradb.zbx
2020-12-23 11:19:03,191___main___40_zabbix_sender zbxdb.zbxoradb.zbx error: 2
2020-12-23 11:19:03,193___main___30_removed lock /home/zabbix/zbxdb_sender/zbxdb_sender.lock

What name should I use for creating zabbix Host in UI? I tried using RDS endpoint as well as Zabbix server for Hostname in file $HOME/etc/zbxdb.zbxoradb.cfg but zabbix items shows "no data found" for both cases.

Thanks
Manoj

**Comment by ikzelf** [comment]
Error 2 is a zabbix_sender return status. Not everything is processed.

Look in the contents of your output file. That lists the hostname that should be created in zabbix GUI and linked to the zbxdb template.
That hostname is controlled in your zbxdb.zbxoradb.cfg

Groeten,
Ronald Rood

**Comment by manoj-alwani** [comment]
Output file doesn't show anything for hostname. I have attached the latest copy of $HOME/zbxdb_out/zbxdb.zbxoradb.zbx

[zbxdb.zbxoradb.zbx.txt](https://github.com/ikzelf/zbxdb/files/5736355/zbxdb.zbxoradb.zbx.txt)

Here's my config file:

$ cat $HOME/etc/zbxdb.zbxoradb.cfg
[zbxdb]
db_url = //zbxoradb.*******.***.rds.amazonaws.com:1521/ORCL
username = cistats
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = zbxoradb.*******.***.rds.amazonaws.com
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs
password_enc = 

I've removed password and masked the RDS endpoint.

Also the error is intermittent. It appears most of time but not all the time. However there's no data found for zbxdb keys in zabbix host.

I also see lot of zip files under $HOME/zbxdb_sender/archive/ directory.

Is there a way that I can debug/output the zabbix_sender command that zbxdb_sender uses?

Thanks
Manoj

**Comment by ikzelf** [comment]
Your hostname is zbxoradb.
You might want to clear the site_checks parameter. I made them as an example in case you want to do some site specific checks. Removing these will decrease the errors.

I think it is mostly working ok. Debugging can be done by splitting. The file in smaller parts until you can identify the culprit[s]

Groeten,
Ronald Rood

**Comment by manoj-alwani** [comment]
Thanks Ronald,

I realize that zabbix_sender was probably working fine. There were some keys that were reporting values properly while some key's value had wrong data format and then there were few keys with no data found.

After updating hostname to zbxoradb (I earlier used the fully qualified domain) in both zbxdb conf file as well in zabbix console, all metrics are working properly.

Thanks
Manoj
