### ISSUE TITLE
 zabbix_sender zbxdb.odb.zbx error: 2

### ISSUE THREAD

**Issue by baramann72** [ikzelf/zbxdb#63]
Hi,

i try to configure your smart solution to monitor some RAC cluster´s with multi databases and instances.
so, in my first steps, i do a basic configure of the scripts an get a result. 
...
db1 "inst[DB12C1,processes]" 1611612624 89
...
When I do a:  $HOME/.bash_profile;$HOME/zbxdb/bin/zbxdb_sender.py -c /etc/zabbix/zabbix_agentd_db1.conf -z zbxdb_out -v

My result:  
2021-01-25 22:01:25,912___main__ Logging in /home/db/log/zbxdb_sender.log
2021-01-25 22:01:25,912___main__ Namespace(cfile='/etc/zabbix/zabbix_agentd_db1.conf', verbosity=1, zbxdb_out='zbxdb_out')
2021-01-25 22:01:25,913___main__ Using /etc/zabbix/zabbix_agentd_db1.conf
2021-01-25 22:01:25,913___main__ 2021-01-25-2201 processing zbxdb.odb.zbx
2021-01-25 22:01:25,915___main__ zabbix_sender zbxdb.odb.zbx error: 2
2021-01-25 22:01:25,916___main__ removed lock /home/db/zbxdb_sender/zbxdb_sender.lock

On zabbix site, i have a host "db1" mapped with your template. 

Software: Ubuntu, 20.04 followed by your documentation ia pyenv 3.6.5, 
Zabbix Server: 5.2, 
Agent: Agent2 V5.2

Thanks for help
Bjoern

**Describe the bug**

**To Reproduce**
1. cfg file  obfuscate entries like address, username and password
2. driver version
3. db version
4. monitoring platform
5.  failing SQL

**Expected behavior**

**logs**
If applicable, add logs to help explain your problem.

**monitoring platform:**
 - distribution, version
 - python version
 - driver version

**Additional context**

**Comment by ikzelf** [comment]
Do you see data arriving in latest data?
What is in zbxdb.odb.zbx?

Zabbix_sender is not very clear about what it has problems with.

**Comment by baramann72** [comment]
hm, strange...I see latest data in zabbix, I believe it was an OSI 8 problem :-)

now i try to understand in detail your framework. in know linux a little bit, but i am not a programmer, so looking and understand your  scripts is very complicated for me. the next step is to get information how I monitor the ASM part of the RAC. there are some cfg file in the etc/zbxdb_check/ but i am not sure what should I do to do this?

and one more question: Is there a way to auto discover all installed databases on a RAC or need I configure them manually? for example, add one zabbix host ABC with the name of the database, add a new cfg in etc like zbxdb.odb_ABC.cfg?

thanks
bjoern

**Comment by ikzelf** [comment]
Hi Bjoern,
for the asm part use a cfg with instance_type asm and a role sysdba.
For database discovery you can use the zbx_orabd_discover.py.
This needs an input file where the list of hosts needs to be listed.
You will need to create the cfg files manually.

There used to be a drawback in this kind of host discovery: zabbix did not allow to edit things like macro values. I am not sure what the current status is.
Check the docu in zbxdb for Oracle. I wrote quite a bit. If in the end you see improvements in docu, create a pull request for that.

**Comment by ikzelf** [comment]
Hi Bjoern,
did you get what you was hoping for?

**Comment by baramann72** [comment]
hi Ronald,
yes it is very interesting, but my time slot for tests are small :-)
The ASM monitoring is running, but know i have the "zbxdb restarted" issue, I configured as you describe, a dependency with the host boot time, but i did not fix it. The interesting thing is, thst this only happend, when two database monitoring cg´s are active, for example "normal" db and the ASM. Perhpas do you have an idea?

My next step is, adjust the monitoring points and time interval for these point. In the default template configuration incl linux os, i have over 500 metrics value for 1 host in a 2 node rac with 1 db and two instances - that is a lot of and "Door de bomen zie je het bos niet meer".  some of the metrics are really important like table space, some values are interesting to know for a dba like query statistics.  my goal is to monitor a rac with nearly 100 databases and with these unfiltered template we will have an very bigger monitor load then normal workload :-)

so, i will keep your up to date with my results :-)

thanks
bjoern

**Comment by ikzelf** [comment]
Hi Bjoern,

if you use the starter script, it distributes the starts of all monitors in such a way that zbxdb does not cause spikes. Every instance of zbxdb mostly sleeps and tries to wake up on the same second. So inst1 works on second 0, inst2 on second 1 ..... every minute. If the statistics are correct, and the recycle bin is empty, they are all in ms.

Timing is controlled in the checks_files. Some run every minute, some every 5 mins, every 60 and even once a day. Be careful with changes here. The interval does have a relation with volatility and availability.

You said zbxdb is constantly restarting? Is that in the logs or is that in the zabbix console? I did put some effort in it to have zbxdb.py as stable as possible. No memory leaks, no cpu crunching. Normally zbxdb.py only restarts when it’s host does restart, when the script, the driver or the logging config changes. When a checks_file changes, it just reloads them in the run.

Groeten,
Ronald Rood

**Comment by ikzelf** [comment]
Did you get this up?

**Comment by baramann72** [comment]
Hi Ronald,

thanks for asking.

In the last days zbxdb leave my home lab and arrives our company test
environment 😊

During I made some tests, I got some ideas around for zbxdb

 1. classification of databases

Reason: To set a monitoring interval bases on classification to set a
monitoring interval multiplicator

 1. Mission critical: Default values (Interval 1 Minute)
 2. Critical: 5 = Interval 5 Minutes
 3. Normal 10 = Interval 10 minutes
 4. Low = interval 60 minutes

 2. Configuration parameter for old data

         When the zbxdb agent is running and deliver successful data to
Zabbix, it is not important to save old data. A parameter to define how
much in size and/or how long the data is stored

     3.     configuration of the tests in a own config file

         A configuration file  how control which tests should running.
On this way, your files do not need a editing and should be untouched.
also useful in case of updates then your files can be overwritten
without data loss. This test control file could also have an statement
for a in include diredtory like conf.d for own configuration an
scripts/sql statements.

After that, i have a question about the best way to monitor the ASM.
Connection to the ASM via SCAN is not possible. So I query each ASM
instance server directly, the result is, that i got monitoring data
twice - is this correct way or you have an idea?

My plan is to play next week with the autodisover. Do i understand
right, this this can be done only with PDB´s?


Thanks
Bjoern


Am 14.02.2021 um 17:05 schrieb Ronald Rood:

**Comment by ikzelf** [comment]
Hi Bjoern,

I am not sure if I understand you correctly but you can control how much data arrives in your database using pre processing. In the current check files I set some frequencies based on my own oracle knowledge.... Availability is important and has a high frequency. Storage for permanent tablespaces is most of the times regular and a hourly query mostly ok. Temporary and undo is more volatile so every 5mins....

I am thinking about how to make those polling frequencies controllable from the zabbix GUI. Not easy to do but I don’t believe in can’t...😎🤔

For your asm monitoring you should give the connection string with the complete address list. One cluster has one ASM configuration that is accessible from each host that is part of the cluster. Use that for the monitoring.

Groeten,
Ronald Rood

**Comment by ikzelf** [comment]
Hi Bjoern,

do you need more help/explanation on this? (also, feel free to make additions or adjustments to whatever that you think is helpful for others (I am open for pull requests))
