### ISSUE TITLE
zbxdb.py

### ISSUE THREAD

**Issue by rmdolezal** [ikzelf/zbxdb#64]
Hi Ronald,
i tryed to use the updated zbxdb.py, but I received following errors:

Wed Feb 17 13:33:24 CET 2021 Starting etc/zbxdb.srvspsdbprod01-SKESPP.odb.cfg
/home/zbxdb/zbxdb/bin/zbxdb.py: line 7: syntax error near unexpected token `newline'
/home/zbxdb/zbxdb/bin/zbxdb.py: line 7: `<!DOCTYPE html>'

when I returned to backed up zbxdb.py, everything is ok .

Regards

Marek

**Comment by rmdolezal** [comment]
aha -mea culpa , badly downloade
please forget

**Comment by rmdolezal** [comment]
bad download

**Comment by ikzelf** [comment]
pfew ... glad you found it.
