### ISSUE TITLE
oracle data guard

### ISSUE THREAD

**Issue by rmdolezal** [ikzelf/zbxdb#65]
Hi Ronald, 
I want to monitor db under oracle data guard - is there any docs about the configuration or config examples about how to monitor primary and standby DBs ?

Thank you 

Marek

**Comment by ikzelf** [comment]
Hi Marek,

zbxdb will detect the role of the database and load the standby related checks file. If your database is only mounted, you need to connect as sysdba. If you have active data guard you can use as regular user, assuming the standby database is open for read only. Nothing special for that.

**Comment by ikzelf** [comment]
Hi Marek,

did you find what you need?
