### ISSUE TITLE
Some items failed

### ISSUE THREAD

**Issue by d1nd141** [ikzelf/zbxdb#71]
Hi,

i deployed zbxdb to a RHEL 7.x Proxy (V 5.0.8) as you describe in the doc.
The scripts are all running (cron) and gathering data.
The following templates are deployed to a host. (took them all to be sure)
template zbxdb (V4_EN)
template zbxdb_alertlog
zbx_tnslsnr

I monitor an oracle 11 instance.
Config:
```
[zbxdb]
db_url = //oradbt1:1527/IAM10T
username = cyxcycycycycy
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = oradbt1
checks_dir = etc/zbxdb_checks
site_checks = primary.11
password_enc = yxyxxycxccyccycycyc

```

I modified the sender py to echo the output of zabbix_sender:

`2021-03-11 08:41:02,177___main___30_Logging in /home/zbxdb/log/zbxdb_sender.log
2021-03-11 08:41:02,178___main___30_Namespace(cfile='/home/zbxdb/zabbix_agentd.conf', verbosity=0, zbxdb_out='zbxdb_out')
2021-03-11 08:41:02,178___main___30_Using /home/zbxdb/zabbix_agentd.conf
2021-03-11 08:41:02,178___main___30_File zbxdb.oradbt1.zbx
2021-03-11 08:41:02,178___main___30_2021-03-11-0841 processing zbxdb.oradbt1.zbx
2021-03-11 08:41:02,179___main___30_Part1
2021-03-11 08:41:02,188___main___30_Err:
2021-03-11 08:41:02,189___main___30_Output: zabbix_sender [111190]: DEBUG: In zbx_tls_init_child()
zabbix_sender [111190]: DEBUG: OpenSSL library (version OpenSSL 1.0.2k-fips  26 Jan 2017) initialized
zabbix_sender [111190]: DEBUG: zbx_tls_init_child() loaded PSK identity "PSK agent-prod"
zabbix_sender [111190]: DEBUG: zbx_tls_init_child() loaded PSK from file "/etc/zabbix/psk_agent.conf"
zabbix_sender [111190]: DEBUG: zbx_tls_init_child() PSK ciphersuites: PSK-AES128-CBC-SHA
zabbix_sender [111190]: DEBUG: End of zbx_tls_init_child()
zabbix_sender [111195]: DEBUG: In zbx_tls_connect(): psk_identity:"PSK agent-prod"
zabbix_sender [111195]: DEBUG: zbx_psk_client_cb() requested PSK identity "xxxxxxxxxx"
zabbix_sender [111195]: DEBUG: End of zbx_tls_connect():SUCCEED (established TLSv1.2 PSK-AES128-CBC-SHA)
zabbix_sender [111195]: DEBUG: answer [{"response":"success","info":"processed: 27; failed: 32; total: 59; seconds spent: 0.000460"}]
Response from "proxyxxxxxxxxxx:10051": "processed: 27; failed: 32; total: 59; seconds spent: 0.000460"
sent: 59; skipped: 0; total: 59

2021-03-11 08:41:02,189___main___40_zabbix_sender zbxdb.oradbt1.zbx error: 2
2021-03-11 08:41:02,196___main___30_removed lock /home/zbxdb/zbxdb_sender/zbxdb_sender.lock
`

in zbxdb_out/zbxdb.oradbt1.zbx i have:

```
oradbt1 "zbxdb[uptime]" 1615448342 65820
oradbt1 "zbxdb[opentime]" 1615448342 65820
oradbt1 "blocked[count]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,blocked,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,blocked,ela]" 1615448342 0.0015801440458744764
oradbt1 "zbxdb[query,checks_01m,blocked,fetch]" 1615448342 0.000155717134475708
oradbt1 "db[IAM10T,openstatus]" 1615448342 3
oradbt1 "zbxdb[query,checks_01m,db.openmode,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,db.openmode,ela]" 1615448342 0.0011672270484268665
oradbt1 "zbxdb[query,checks_01m,db.openmode,fetch]" 1615448342 8.466118015348911e-05
oradbt1 "inst[IAM10T,uptime]" 1615448342 76462755
oradbt1 "zbxdb[query,checks_01m,inst.uptime,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,inst.uptime,ela]" 1615448342 0.0009374278597533703
oradbt1 "zbxdb[query,checks_01m,inst.uptime,fetch]" 1615448342 0.00013694213703274727
oradbt1 "db[current_scn]" 1615448342 131754026
oradbt1 "db[delta_scn]" 1615448342 131754026
oradbt1 "zbxdb[query,checks_01m,scn,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,scn,ela]" 1615448342 0.0014892912004143
oradbt1 "zbxdb[query,checks_01m,scn,fetch]" 1615448342 0.0006130489055067301
oradbt1 "inst[IAM10T,sessions]" 1615448342 115
oradbt1 "inst[IAM10T,processes]" 1615448342 118
oradbt1 "inst[IAM10T,execute count]" 1615448342 323694295
oradbt1 "inst[IAM10T,DB time]" 1615448342 3994373079
oradbt1 "inst[IAM10T,user calls]" 1615448342 238289261
oradbt1 "zbxdb[query,checks_01m,sysstat,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,sysstat,ela]" 1615448342 0.007162200985476375
oradbt1 "zbxdb[query,checks_01m,sysstat,fetch]" 1615448342 0.0012631099671125412
oradbt1 "zbxdb[query,checks_01m,,ela]" 1615448342 0.013307664077728987
oradbt1 "blocked[count]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,blocked,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,blocked,ela]" 1615448342 0.0014939899556338787
oradbt1 "zbxdb[query,checks_01m,blocked,fetch]" 1615448342 5.7579949498176575e-05
oradbt1 "db[IAM10T,openstatus]" 1615448342 3
oradbt1 "zbxdb[query,checks_01m,db.openmode,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,db.openmode,ela]" 1615448342 0.001057968009263277
oradbt1 "zbxdb[query,checks_01m,db.openmode,fetch]" 1615448342 9.520095773041248e-05
oradbt1 "inst[IAM10T,uptime]" 1615448342 76462755
oradbt1 "zbxdb[query,checks_01m,inst.uptime,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,inst.uptime,ela]" 1615448342 0.0011447540018707514
oradbt1 "zbxdb[query,checks_01m,inst.uptime,fetch]" 1615448342 0.00010040099732577801
oradbt1 "db[current_scn]" 1615448342 131754028
oradbt1 "db[delta_scn]" 1615448342 131754028
oradbt1 "zbxdb[query,checks_01m,scn,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,scn,ela]" 1615448342 0.0017281158361583948
oradbt1 "zbxdb[query,checks_01m,scn,fetch]" 1615448342 0.0008239410817623138
oradbt1 "inst[IAM10T,sessions]" 1615448342 115
oradbt1 "inst[IAM10T,processes]" 1615448342 118
oradbt1 "inst[IAM10T,execute count]" 1615448342 323694300
oradbt1 "inst[IAM10T,DB time]" 1615448342 3994373079
oradbt1 "inst[IAM10T,user calls]" 1615448342 238289268
oradbt1 "zbxdb[query,checks_01m,sysstat,status]" 1615448342 0
oradbt1 "zbxdb[query,checks_01m,sysstat,ela]" 1615448342 0.006123590981587768
oradbt1 "zbxdb[query,checks_01m,sysstat,fetch]" 1615448342 0.0009427880868315697
oradbt1 "zbxdb[query,checks_01m,,ela]" 1615448342 0.012648676987737417
oradbt1 "zbxdb[query,,,ela]" 1615448342 0.027172040194272995
oradbt1 "zbxdb[cpu,user]" 1615448342 7.546029
oradbt1 "zbxdb[cpu,sys]" 1615448342 3.7478949999999998
oradbt1 "zbxdb[mem,maxrss]" 1615448342 27860
oradbt1 "zbxdb[connect,status]" 1615448342 0

```
F.ex i dont have an item key "zbxdb[query,checks_01m,sysstat,ela]" assigned to the host oradbt1.

Any idea why i have failed events, or why they are not in the template?
Missed i something?
Thanks

**Comment by ikzelf** [comment]
Hi, running with a higher verbosity would accomplish about the same logging.
Yes, a good chance items are not all in the template. If you want them, add them. I am quite sure there are more points of interest.
I am open for pull requests.

For the offline servers: what I do is simply prepare a virtual env on a Vm with the same OS, quickly test for import errors and copy the ~/.pyenv directory to the machine. It contains the complete python installation with all dependencies. Maybe not the most fancy method but it works like a charm.

**Comment by ikzelf** [comment]
I almost forgot: "zbxdb[query,checks_01m,sysstat,ela]" is a zbxdb internal item for which the discovery is only passed during the database connection. At that point in time the queries are all read and passed to zabbix. The idea is to have some metrics about the zbxdb query performance. Sometimes they are hurt by stale statistics or a filled dba recycle bin.

**Comment by ikzelf** [comment]
Do you need more help?

**Comment by d1nd141** [comment]
Hello,
thanks for your help!
I had no time yet to test further.
But my superior decided to use the default template provided from Zabbix, even if not perfect!!
It will be difficult for a non dba admin to decide which items to keep, and which triggers do configure etc.

**Comment by ikzelf** [comment]
That’s a pity since they are a bit limited and monitoring using the agent and doing so will have a hard time monitoring availability and more complex configurations.
And yes, you need to involve a dba to make sure your database monitoring makes sense.
Zabbix also sees their templates as an example of how it could be done.
