### ISSUE TITLE
oracle stby db

### ISSUE THREAD

**Issue by rmdolezal** [ikzelf/zbxdb#77]
Hi Ronald, 
I tryed to monitor stby db but I have a problem with login to db - because of stby. So I cant login as user zabbix. How can I solve the problem ? How the cfg file must look ?

Thank you

Regards

Marek

2021-04-19 12:33:17,910___main___20_site_checks       : standby.12

2021-04-19 12:33:17,911___main___20_connecting to zabbix/******@// - removed

2021-04-19 12:33:18,108___main___50_problem
Traceback (most recent call last):
  File "/home/zbxdb/zbxdb/bin/dbconnections/oracle.py", line 97, in connect
    _x = _db.connect(connect_string(_c), mode=_c['omode'])
cx_Oracle.DatabaseError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by ikzelf** [comment]
Hi Marek,

I assume that the standby is not open for read only. In that case you need to connect as sysdba. You can connect as sysdba to specifying the "role = sysdba" in the cfg.
And of course you need to grant sysdba to your monitoring user.

Ronald.

**Comment by rmdolezal** [comment]
Hi Ronald,
Yes, role=sysdba was the trick 😊
Now it`s working.  Thank you for your outstanding work.

Best regards

Marek

**Comment by ikzelf** [comment]
glad it's working as designed :-D
