### ISSUE TITLE
zbxdb monitor oracle cluster?

### ISSUE THREAD

**Issue by wang509020** [ikzelf/zbxdb#79]
hi @ikzelf 
good evening ,I working in the night  day, and working with oracle for zabbix monitor.so I see you zbxdb, is very good ,for my zabbix monitor,my follows:
zabbix server 5.2.4
zabbix proxy 5.2.4( and zbxdb software in it)
zabbix agent 5.2.4(the oracle databases have very much  servers)
so,I see your software-zbxdb, the oracle's config is etc/zbxdb.odb.cfg,
  db_url = //localhost/fsdb01      #and here is only to a host, no many host,because the oracle's user and pwd isn't the same.
 
so, I will do it ?pls tell me ,tks

**Comment by wang509020** [comment]
and I see the software zbxdb, discovery zbxdb monitor sqlserver,is very storage,so I test it for sqlserver,now I will for oracle ,the is important,pls tell me ,tks

**Comment by ikzelf** [comment]
The zbxdb.odb.cfg is just an example with name ‘odb’.  You need to create one similar file for every oracle database.
Call them zbxdb.{yourdb}.cfg
Zbxdb_starter will take care of starting the processes in such a way that the distribute their activity over time to prevent cpu spikes.

**Comment by wang509020** [comment]
wo
I see ,tks  very much , I do it ,test

**Comment by wang509020** [comment]
@ikzelf 
I'm sorry ,discovery question:
2021-04-27 04:18:49,354___main___20_connecting to zabbix/******@(vn-smt-p=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ynmese-scan)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ynmese))))

2021-04-27 04:18:49,358_dbconnections.oracle_40_connect failed 12533 with ORA-12533: TNS:illegal ADDRESS parameters
2021-04-27 04:18:49,359___main___40_(8.11)connection error: [12533] ORA-12533: TNS:illegal ADDRESS parameters for zabbix@(vn-smt-p=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ynmese-scan)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ynmese))))
the server's config  etc/zbxdb.ynmese1.cfg
$ cat ../etc/zbxdb.ynmese1.cfg
[zbxdb]
db_url = (vn-smt-p=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ynmese-scan)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ynmese))))
username = zabbix
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = ynmese1
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs
password_enc = emFiYml4XzEyMw==

my question:why don't tns connect the oracle?

**Comment by wang509020** [comment]
pls see my a host's oracle connection and it's config:
[zbxdb]
db_url = vn-smt-p=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ynmese-scan)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=ynmese)))                 #here is use TNS connect,but i don't know it true or fail
username = zabbix                                #dba create user
password =                                             #dba create user's passwd,but now don't show the pwd
db_type = oracle                                       #I don't modify it ,I monitoring oracle database
db_driver = cx_Oracle                               #python connect oracle's python script tools
instance_type = rdbms                              #the instance_type  is not modify it ,but I keep it 
role = sysdba                                              #the role have two role:normal or sysdba
out_dir = $HOME/zbxdb_out                     
hostname = ynmese1                                #oracle host's hostname
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs                                   #the checks list,is it modify?
password_enc = emFiYml4XzEyMw==
pls know it tell me ,thks.

**Comment by ikzelf** [comment]
You can clear the site_checks parameter.
Normally you use the normal role to connect and a regular low privileged user to connect. Sysdba is only needed for asm and for standby databases that are not open.
Use the url like you would use with sqlplus with ezconnect to connect.

**Comment by ikzelf** [comment]
Your last connect url looks like it is ok. The others were not balanced correctly.
The log will tell if the process is connected and report the instance, Sid, serial# and spid. Next to that it will start generating files in the zbxdb_out directory containing data.

**Comment by ikzelf** [comment]
For db_url, use the ezconnect string or the value of the tns alias, like in a thin jdbc connect string like: (DESCRIPTION=(ADDRESS=(HOST=myhost)(PORT=1521)(PROTOCOL=tcp))(CONNECT_DATA=(SERVICE_NAME=myorcldbservicename)))

**Comment by wang509020** [comment]
ok,
very good
I modify etc/zbxdb/ynmese1.cfg
db_url = //10.171.7.60:1521/ynmese    
now zabbix get the oracle data, is very good,

**Comment by ikzelf** [comment]
And for RAC, don’t forget to use the scan listener. Using the global views zbxdb monitors all instances.

**Comment by ikzelf** [comment]
Oh and I almost forgot: you can also use tns aliases and tnsnames.Ora if you want. Just make sure that TNS_ADMIN is defined(or ORACLE_HOME)

**Comment by ikzelf** [comment]
since it's working now closing.

**Comment by wang509020** [comment]
hi,
sorry, I do other this time,now ,I look at your answer,thks,
now,I have a question:
asm,asmvg,acfs isn't discovery item,why,pls help me ,thanks.


and I must set etc/xxx.cfg,pls tell me ,

**Comment by faciulula** [comment]
Zabbix -> Administration -> General -> Regular Expressions -> File systems for discovery -> Add this "asm|asmvg|acfs|" before "btrfs".

**Comment by ikzelf** [comment]
They are also discovered via the ASM instances. When using acfs there are extra asm instances. They have to be monitored to get the volume stats.

**Comment by nivethaasr** [comment]
Hello @ikzelf 

I am trying to configure zabbix for oracle RAC ( 4 nodes with two nodes having active databases and two on standby , each node has lot of instances running ) , I would want to connect to the database and not to instances to monitor . Please let me know how I can configure .

**Comment by ikzelf** [comment]
Configure and use a tnsnames.ora that uses the address list for the alias that you want to monitor. That is probably the easiest way to do.

**Comment by nivethaasr** [comment]
I'm using zabbix 7.0.2 and the default oracle template . Should I use sysdba to monitor the database on RAC and any standby databases ?

**Comment by ikzelf** [comment]
sysdba is only needed when you need to monitor a standby database that is not open for read.

**Comment by nivethaasr** [comment]
Thank you Sir , In a RAC set up where I have many databases running on each node . I can configure each host separately in the zabbix front end and the {$ORACLE.SERVICE} can be the database name instead of the instance ?

**Comment by nivethaasr** [comment]
Hello @ikzelf ,

I'm trying to set up zabbix for RAC and configured tnsnames.ora file on the server . I have the node pointing to the database directly ( not the instance ) . I have set the environment variables in zabbix-agent2 , the oracle_home,ld_library_path and tns_admin to point to the tnsnames.ora file on the server ( not the SCAN listener) . I get this error in zabbix -  ORA-12541: TNS:no listener . So I tried poiting the tns_admin variable to scan listener path, but still got the same error , Could you please kindly help me on this .

**Comment by ikzelf** [comment]
You are writing in a 4 year old issue in zbxdb that is closed.
You are also not having an issue with zbxdb but what zabbix made in agent2.
I have not yet looked in how to configure that.

**Comment by nivethaasr** [comment]
Hello Sir , thank you for the reply , Yes, I pointed the alias to the database but the listener is not being recognized by the agent. That's where I'm stuck at .

**Comment by ikzelf** [comment]
Ask your local dba. I don't have your config of the database. Test with a native sqlplus client to test your tnsnames.ora. If that works go to the agent2 config.
Does the agent2 use the client libs at all?
