### ISSUE TITLE
zabbix monitor oracle asm, isn't monitor?

### ISSUE THREAD

**Issue by wang509020** [ikzelf/zbxdb#80]
Hi
@ikzelf ,Sorry,I have a question,help me 
![image](https://user-images.githubusercontent.com/50124188/117390369-9e06eb80-af20-11eb-8106-546b3da9b4ef.png)
I can't discovery asm,and the etc/zbxdb.ynmese1.cfg:
#$ cat zbxdb.ynmese1.cfg
[zbxdb]
db_url = //10.171.7.60:1521/ynmese
username = zabbix
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = ynmese1
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs
password_enc = emFiYml4XzEyMw==

now,pls tell me how set asm's item,thks.

**Comment by wang509020** [comment]
sorry,supplement:
#log/zbxdb.ynmese1.cfg.log
2021-05-07 09:33:40,909___main___20_key=ebs_10m.ebs.concmgr ZBXDB-942: Db execution error: ORA-00942: table or view does not exist

2021-05-07 09:33:40,911___main___20_key=ebs_10m.ebs.paul.truncatp ZBXDB-942: Db execution error: ORA-00942: table or view does not exist

**Comment by ikzelf** [comment]
Remove the site_checks parameter.
Specify instance_type asm instead of rdbms.
Specify the role sysdba instead of normal.
Assign a new hostname for the asm configuration.

Groeten,
Ronald Rood

**Comment by wang509020** [comment]
this question ,I test it laster.
now ,the question is very hard,i don't why ?
![image](https://user-images.githubusercontent.com/50124188/117415689-2c906280-af4b-11eb-9ef5-24471b14ee83.png)
I use zbxdb now monitor two oracle  database,
but yneda and ynmese1 monitoring data to a computer,and other computer is not data,why?
![image](https://user-images.githubusercontent.com/50124188/117416014-885aeb80-af4b-11eb-927e-8fa64fe43d61.png)
![image](https://user-images.githubusercontent.com/50124188/117416146-a7597d80-af4b-11eb-8f8e-162314190b2c.png)

**Comment by ikzelf** [comment]
I am not sure what you mean. Normally I expect a host that represents a database, that has the zbxdb template assigned to it, plus maybe some site specific additional templates that hold other data from that same database.

Their hosts have the OS templates.

You could have multiple database instances on a single Linux server.

A RAC database uses multiple Linux servers but still this is just a single database for which you create a single host with the zbxdb template assigned to it.

Groeten,
Ronald Rood

**Comment by wang509020** [comment]
cat zbxdb.yneda.cfg
[zbxdb]
db_url = //10.171.7.56:1521/yneda
username = zabbix
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = asm
role = sysdba
out_dir = $HOME/zbxdb_out
hostname = yneda
checks_dir = etc/zbxdb_checks
#site_checks = sap,ebs
password_enc = emFiYml4XzEyMw==

I modify the file,and log is error for it 
2021-05-07 16:15:12,515___main___20_connecting to zabbix/******@//10.171.7.56:1521/yneda

2021-05-07 16:15:13,537_dbconnections.oracle_40_connect failed 1017 with ORA-01017: invalid username/password; logon denied
2021-05-07 16:15:13,538___main___40_(2.11)connection error: [1017] ORA-01017: invalid username/password; logon denied for zabbix@//10.171.7.56:1521/yneda
why ,pls help me

**Comment by ikzelf** [comment]
You probably did not grant sysdba to that user.

**Comment by ikzelf** [comment]
And, for asm, you normally connect to the asm instance, not to the rdbms instance.

**Comment by ikzelf** [comment]
I assume this is working now.

**Comment by Heloiseboanerges** [comment]
@ikzelf Good day!
I'm experiencing a similar error when trying to monitor my ASM instance... 
It seems that, the login is not created as SYSDBA... :(

![image](https://user-images.githubusercontent.com/40353290/166483235-dc173765-9cf4-4159-84d7-b07f1431bff7.png)

I've tried using the cfg file for zbxdb.oracle-cluster1-ASM.cfg and the zbxdb.odb.cfg.... changing the connection string... but no clue:

[zbxdb]
db_url = //172.24.130.197:1521/+ASM
username = zabbix_mon
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = asm
role = sysdba
out_dir = $HOME/zbxdb_out
site_checks =
hostname = P6PRODASM
checks_dir = etc/zbxdb_checks
password_enc = 

![image](https://user-images.githubusercontent.com/40353290/166483881-34738fb3-8e7f-4a26-8467-ba26c99e1bb6.png)

Is there something I'm missing? For the DB instance works as expected (is a dataguard standby, so, the sysdba has been granted for the user...)
