### ISSUE TITLE
If in zabbix-agent2 config cert encryption is enabled -> error 2

### ISSUE THREAD

**Issue by JustNZ** [ikzelf/zbxdb#81]
**Describe the bug**
zbxdb is installed on my proxy server with an agent configuration of encrypted cert communication.

If cert encryption is commented out in the zabbix_agent2.conf, zbxdb is working without any errors.
But if I uncomment cert encryption (connect, accept) I get error 2 in zbxdb_sender.log

**To Reproduce**
1. cert encryption enabled
2. zbxdb log reports error 2

**Expected behavior**
zbxdb working with cert encryption 

**logs**
2021-05-17 10:09:02,229___main___30_2021-05-17-1009 processing zbxdb.DB.zbx
2021-05-17 10:09:02,246___main___40_zabbix_sender zbxdb.DB.zbx error: 2

**monitoring platform:**
 - Zabbix Server, Proxy, Agent Version = 5.0.8
 - python version = 3.6.5

**Additional context**

**Comment by JustNZ** [comment]
and if for example TLSCAFile is not commented out - zbxdb reports error: 1

**Comment by ikzelf** [comment]
Hi,
this is a problem with zabbix_sender. Could you check the version of zabbix_sender and bring it to the same version as the agent?

**Comment by JustNZ** [comment]
Hey,
zabbix_sender is on the same version as zabbix_agent2:

zabbix-agent2.x86_64                5.0.8-1.el7   
zabbix-apache-conf-scl.noarch       5.0.8-1.el7  
zabbix-java-gateway.x86_64          5.0.8-1.el7
zabbix-proxy-sqlite3.x86_64         5.0.8-1.el7 
zabbix-sender.x86_64                5.0.8-1.el7
zabbix-server-pgsql.x86_64          5.0.8-1.el7   
zabbix-web.noarch                   5.0.8-1.el7  
zabbix-web-deps-scl.noarch          5.0.8-1.el7 
zabbix-web-pgsql-scl.noarch         5.0.8-1.el7

**Comment by ikzelf** [comment]
So, with encryption enabled in the agent config no data arrives from zbxdb at all?
That's a bit strange. To prevent this kinds of problems I changed to using the agent config in the first place assuming that all would be handled nicely by zabbix-sender.
[https://www.zabbix.com/documentation/5.0/manpages/zabbix_sender](https://www.zabbix.com/documentation/5.0/manpages/zabbix_sender)
-c, --config config-file
Use config-file. Zabbix sender reads server details from the agentd configuration file. By default Zabbix sender does not read any configuration file. Only parameters Hostname, ServerActive, SourceIP, TLSConnect, TLSCAFile, TLSCRLFile, TLSServerCertIssuer, TLSServerCertSubject, TLSCertFile, TLSKeyFile, TLSPSKIdentity and TLSPSKFile are supported. All addresses defined in the agent ServerActive configuration parameter are used for sending data. If sending of batch data fails to one address, the following batches are not sent to this address.

Does the zbxdb-sender process have access to the TLSCAFile ? I can imagine this will cause a problem if this file is not readable.

**Comment by JustNZ** [comment]
I copied all relevant cert files in the home directory of the correct user and granted permissions - zbxdb still throws error: 2

My file permissions:
`-rw-r--r-- 1 zabbix root   1180 17. Mai 12:14 ca.pem
-rw-r--r-- 1 zabbix root   1069 17. Mai 12:14 host.crt
-r-------- 1 zabbix root   1703 25. Feb 12:25 host.key`

zabbix-agent2 tls config:
`####### TLS-RELATED PARAMETERS #######

### Option: TLSConnect
#       How the agent should connect to server or proxy. Used for active checks.
#       Only one value can be specified:
#               unencrypted - connect without encryption
#               psk         - connect using TLS and a pre-shared key
#               cert        - connect using TLS and a certificate
#
# Mandatory: yes, if TLS certificate or PSK parameters are defined (even for 'unencrypted' connection)
# Default:
# TLSConnect=unencrypted

TLSConnect=cert

### Option: TLSAccept
#       What incoming connections to accept.
#       Multiple values can be specified, separated by comma:
#               unencrypted - accept connections without encryption
#               psk         - accept connections secured with TLS and a pre-shared key
#               cert        - accept connections secured with TLS and a certificate
#
# Mandatory: yes, if TLS certificate or PSK parameters are defined (even for 'unencrypted' connection)
# Default:
# TLSAccept=unencrypted

TLSAccept=cert

### Option: TLSCAFile
#       Full pathname of a file containing the top-level CA(s) certificates for
#       peer certificate verification.
#
# Mandatory: no
# Default:
# TLSCAFile=

TLSCAFile=/etc/zabbix/certs/ca-swift.pem

### Option: TLSCRLFile
#       Full pathname of a file containing revoked certificates.
#
# Mandatory: no
# Default:
# TLSCRLFile=

### Option: TLSServerCertIssuer
#               Allowed server certificate issuer.
#
# Mandatory: no
# Default:
# TLSServerCertIssuer=

### Option: TLSServerCertSubject
#               Allowed server certificate subject.
#
# Mandatory: no
# Default:
# TLSServerCertSubject=

### Option: TLSCertFile
#       Full pathname of a file containing the agent certificate or certificate chain.
#
# Mandatory: no
# Default:
# TLSCertFile=

TLSCertFile=/etc/zabbix/certs/host.crt

### Option: TLSKeyFile
#       Full pathname of a file containing the agent private key.
#
# Mandatory: no
# Default:
# TLSKeyFile=

TLSKeyFile=/etc/zabbix/certs/host.key

### Option: TLSPSKIdentity
#       Unique, case sensitive string used to identify the pre-shared key.
#
# Mandatory: no
# Default:
# TLSPSKIdentity=

### Option: TLSPSKFile
#       Full pathname of a file containing the pre-shared key.
#
# Mandatory: no
# Default:
# TLSPSKFile=
`

**Comment by ikzelf** [comment]
from the zabbix-sender manpage:
EXIT STATUS

The exit status is 0 if the values were sent and all of them were successfully processed by server. If data was sent, but processing of at least one of the values failed, the exit status is 2. If data sending failed, the exit status is 1.

You have exit status 2. That can have various reasons, most likely there are sql's generating keys that are not in the template.
I expect you to see data coming in now.

**Comment by JustNZ** [comment]
But the weird thing is:

Encryption off = everything fine
Encryption on = everything fails and no data is going into zabbix

Is there anything I could test/do?

**Comment by ikzelf** [comment]
what you can do is unarchive a recent file from zbxdb_out/archive/ and send it manually using
zabbix_sender -c /etc/zabbix/zabbix_agent2.conf -T -i the_extracted_file -vv
An other option is to raise the verbosity so the stdout and stderr of zabbix-sender will be logged.

I really expect/hope that the uptime and the connect,status keys will receive data. They are sampled and sent every minute. With a little luck it shows a bit more of info.

**Comment by ikzelf** [comment]
Did you get any more info from the debug output?

**Comment by JustNZ** [comment]
That is the response

```
[zabbix@Server 2021-05-18-0633]$ zabbix_sender -c /etc/zabbix/zabbix_agent2.conf -T -i zbxdb.DB.zbx -vv
zabbix_sender [130762]: DEBUG: In zbx_tls_init_child()
zabbix_sender [130762]: DEBUG: OpenSSL library (version OpenSSL 1.0.2k-fips  26 Jan 2017) initialized
zabbix_sender [130762]: DEBUG: zbx_tls_init_child() loaded CA certificate(s) from file "/etc/zabbix/certs/ca.pem"
zabbix_sender [130762]: DEBUG: zbx_tls_init_child() loaded certificate(s) from file "/etc/zabbix/certs/host.crt"
zabbix_sender [130762]: DEBUG: zbx_tls_init_child() loaded private key from file "/etc/zabbix/certs/host.key"
zabbix_sender [130762]: DEBUG: zbx_tls_init_child() certificate ciphersuites: ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-RSA-AES128-SHA AES128-GCM-SHA256 AES128-SHA256 AES128-SHA
zabbix_sender [130762]: DEBUG: End of zbx_tls_init_child()
zabbix_sender [130763]: DEBUG: In zbx_tls_connect(): issuer:"" subject:""
zabbix_sender [130763]: DEBUG: zbx_tls_connect() peer certificate issuer:"CN=CA" subject:"CN=Server,O=zabbix development,C=DE"
zabbix_sender [130763]: DEBUG: End of zbx_tls_connect():SUCCEED (established TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256)
zabbix_sender [130763]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 250; total: 250; seconds spent: 0.006800"}]
Response from "127.0.0.1:10051": "processed: 0; failed: 250; total: 250; seconds spent: 0.006800"
zabbix_sender [130764]: DEBUG: In zbx_tls_connect(): issuer:"" subject:""
zabbix_sender [130764]: DEBUG: zbx_tls_connect() peer certificate issuer:"CN=CA" subject:"CN=Server,O=zabbix development,C=DE"
zabbix_sender [130764]: DEBUG: End of zbx_tls_connect():SUCCEED (established TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256)
zabbix_sender [130764]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 72; total: 72; seconds spent: 0.002063"}]
Response from "127.0.0.1:10051": "processed: 0; failed: 72; total: 72; seconds spent: 0.002063"
sent: 322; skipped: 0; total: 322
```

**Comment by JustNZ** [comment]
from my point of view - that looks OK?
But i can't see any new data in Zabbix itself

**Comment by JustNZ** [comment]
The issue is solved and was pretty "stupid" :D 

If you want encrypted connection, then also set the host in zabbix to encrypted connection :D
I enabled certificate connection for my host in the zabbix server and after that all the data got into it.

Sorry for that

**Comment by ikzelf** [comment]
Glad that you found this yourself. And yes, if total equals failed nothing came through. From the logging it is not very clear to me what was wrong but indeed, both sides need to be setup to be able to work with encryption.
