### ISSUE TITLE
Many "zbxdb restarted" problems...

### ISSUE THREAD

**Issue by froodo** [ikzelf/zbxdb#82]
**Describe the bug**
I receive many notification 

"Problem started at 21:00:50 on 2021.05.24 Problem name: zbxdb restarted
Host: dwh
Severity: Information

Original problem ID: 1848954" and 

"Problem has been resolved at 21:00:49 on 2021.05.24 Problem name: zbxdb restarted
Host: dwh
Severity: Information

Original problem ID: 1848950
".

I try to remove to template and add again...

Nothing help...

**monitoring platform:**
 - Zabbix 5.0.12

**Comment by ikzelf** [comment]
This is just an InformationAl message stating that the zbxdb.py process restarted. It does not have to mean there is a problem.
What is in the log?

**Comment by froodo** [comment]
I think I understand my problem.
I have two instance on one windows host. How i can add his on zabbix?
Add two config?
Sample of configs
First config:
[zbxdb]
db_url = //172.16.0.1/dwh
username = zabbix
password =  zabbix
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = dwh
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs
and 

[zbxdb]
db_url = //172.16.0.1/dwh2
username = zabbix
password =  zabbix
db_type = oracle
db_driver = cx_Oracle
instance_type = rdbms
role = normal
out_dir = $HOME/zbxdb_out
hostname = dwh
checks_dir = etc/zbxdb_checks
site_checks = sap,ebs

**Comment by ikzelf** [comment]
You are right.
Since you have dwh and dwh2 both attached to host dwh. Just change the config for one and attach that ine to a new zabbix host dwh2.

You also have the site_checks parameter in use. Do you really have a sap and an ebs installation in your dwh databases? You might want to remove them from your config. They are just an example.

**Comment by ikzelf** [comment]
Did you get this fixed?

**Comment by froodo** [comment]
Yes. All work well! Thanks again. Maybe specify this issue in the documentation? for people with many instance on one host.

**Comment by ikzelf** [comment]
glad you have it all working. I added some docu about this. If you have suggestions to improve, feel free to share.
Thanks.
