### ISSUE TITLE
Template v5 is not in english

### ISSUE THREAD

**Issue by ccbezerra** [ikzelf/zbxdb#83]
Hi,

Is possible translate  zbxdb_template_v5.xml to english ?

I recived this alert "fra zit vol" at this template.

**Comment by ikzelf** [comment]
Hi, thanks for catching this. Feel free to update this and to create a pull request for the translation that I will happily accept to share with all.

**Comment by ikzelf** [comment]
I did translate some item and rule descriptions. The item names is a bit more work and should be done using the GUI since otherwise relations with triggers and calculated items get lost.
