### ISSUE TITLE
Alert: fra is full but the fra is not full

### ISSUE THREAD

**Issue by ccbezerra** [ikzelf/zbxdb#84]
Hi,

I recived the alert "fra is full", but is wrong because my db_recovery_file_dest_size parameter was set up to 0 value. 

I think it's a good idea check db_recovery_file_dest_size parameter before to send this alert.

Oracle version: 11.2.0.4.0
Linux version: Red Hat Enterprise Linux Server release 6.10 (Santiago)
Zabbix server version: 5.4
Zabbix agent version: 5.0
Template: zbxdb_template_v5.xml

**Comment by ikzelf** [comment]
Thanks for the message. 0 kind of means: unlimited. 
How would you like to see this changed?
I can imagine a macro with an upper limit…… (I have no real idea how to handle this other than completely ignoring this in the trigger)

**Comment by ikzelf** [comment]
The query controlling this is:
select 'fra[limit]', space_limit from v$recovery_file_dest def
      union all
     select 'fra[used]', space_used from v$recovery_file_dest def
      union all
     select 'fra[reclaimable]', space_reclaimable from v$recovery_file_dest def
      union all
     select 'fra[files]', number_of_files from v$recovery_file_dest def
      union all
     select 'fra[usable,pct]',decode(space_limit, 0,0,(100-(100*(space_used - space_reclaimable)/space_limit)))
       from v$recovery_file_dest
      union all
     select 'rp', count(*) from v$restore_point;

The trigger checks fra[usable,pct]

**Comment by ikzelf** [comment]
I am not sure what to do with this issue. Do you have a good suggestion?
