### ISSUE TITLE
Oracle, deleted PDB datafile still shows in monitor

### ISSUE THREAD

**Issue by thimself** [ikzelf/zbxdb#85]
Hi,

Problem was encountered in test database where i dropped the whole PDB including datafile. Database still shows in monitoring as "Mounted" and datafile is shown in dataset.

Is there a way for me to clear this from the monitor or should it happen automatically? 

Command used:
DROP PLUGGABLE DATABASE RANDOMNAME INCLUDING DATAFILES;

**Comment by ikzelf** [comment]
This will dissapear automagically once the next pdb discovery has been done. From that point on it will show as no longer discovered and after a while vanish completely. That time depends on the keep period in the discovery rule.

**Comment by ikzelf** [comment]
Did this all work as designed?

**Comment by thimself** [comment]
Hi,

I can confirm that it has worked like planned. Deleted PDB has been automatically removed from the monitor.

**Comment by ikzelf** [comment]
Thanks, glad to hear that. Closing this ticket.
