### ISSUE TITLE
Can't sent table data with huge amount of text

### ISSUE THREAD

**Issue by JustNZ** [ikzelf/zbxdb#87]
**Describe the bug**
I have an sql query which shows me current table lock. But zbxdb is not able to parse the data from the sql query output to my zabbix server/proxy.

If no table is locked the execution of the sql is working fine

**To Reproduce**
1. lock a table
2. wait for zbxdb query run
3. no data shown on zabbix

**Expected behavior**
Get text in zabbix

**logs**
zabbix_sender output:
```
zabbix_sender [81494]: ERROR: [line 169] 'Timestamp' required
Sending failed.
```

data to send with error line:
```
    168 db "db_locks" 1624363147 1:   OBJ: sample.TEST1
    169                 BG: SID=999/99999|INACTIVE|USER/SCHEMA=sample/sample|OSUSER=sample|sqlplus@blur|
    170                 BD: SID=222/222222|ACTIVE|USER/SCHEMA=sample/sample|OSUSER=blur|sample-000001@blur|00mma01hu0v5j

```

**monitoring platform:**
 - Zabbix Server, Proxy, Agent Version = 5.0.8
 - python version = 3.6.5

**Additional context**

**Comment by ikzelf** [comment]
could you show the contents of the zbxdb.py out file for this database?
could you show me the query?
The third field in the output file is the timestamp, in your case that looks a lot like "1624363147" The complaint is about # 169 so could it be that your query generates line feeds?

I have:
blocked: select 'blocked[topsid]', topsid||'('||blocked||')'
          from (
          select final_blocking_instance||'/'||final_blocking_session topsid, count(*) blocked
          from gv$session
          where  FINAL_BLOCKING_SESSION_STATUS='VALID'
          group by final_blocking_instance||'/'||final_blocking_session
          order by 2 desc, 1
          )
          where rownum < 2
          union all
          select 'blocked[count]', ''||count(*)
           from gv$session
           where  FINAL_BLOCKING_SESSION_STATUS='VALID'

This most of the times gives the session blocking the most other sessions.

**Comment by JustNZ** [comment]
our Query is a bit advanced due to complexibility.
What do you mean with "zbxdb.py out file"? the config file?

and yes it could be that the output generate new lines

Query:
```
select 'db_locks' as KEY, SUBSTR( sessions,1,2040)session_cut
                from (
                  select LISTAGG(SUBSTR(sessions_tab,1,395), chr(10)) WITHIN GROUP (ORDER BY sessions_tab desc) sessions
                  from (
                        select blocking_sessions.inst_id||':'||chr(9)||
                        'OBJ: '||o.owner || '.' ||o.object_name ||chr(10)||chr(9)||chr(9)||
                        'BG: SID=' || blocking_sessions.sid ||'/'||blocking_sessions.serial#||'|'||blocking_sessions.status ||
                        '|USER/SCHEMA=' ||blocking_sessions.username||'/'||blocking_sessions.schemaname ||
                        '|OSUSER=' ||blocking_sessions.osuser ||
                        '|' ||REGEXP_REPLACE(blocking_sessions.program,'@.*$','') || '@' ||blocking_sessions.machine ||
                        '|' ||blocking_sessions.sql_id ||chr(10)||chr(9)||chr(9)||
                        'BD: SID=' ||
                        blocked_sessions.sid ||'/' || blocked_sessions.serial#||'|'||blocked_sessions.status ||
                        '|USER/SCHEMA=' ||blocked_sessions.username||'/'||blocked_sessions.schemaname ||
                        '|OSUSER=' ||blocked_sessions.osuser ||
                        '|' ||REGEXP_REPLACE(blocked_sessions.program,'@.*','')||'@'||blocked_sessions.machine ||
                        '|' ||blocked_sessions.sql_id sessions_tab
                        from (
                          select inst_id,sid,serial#,status,username,schemaname,osuser,machine,program,blocking_session,final_blocking_session,
                          row_wait_obj# blocked_objects,sql_id
                          from gv$session
                          where event like 'enq:%' and final_blocking_session_status = 'VALID'
                        ) blocked_sessions,
                        gv$session blocking_sessions,
                        dba_objects o
                        where
                        blocking_sessions.inst_id=blocked_sessions.inst_id and
                        blocking_sessions.sid = blocked_sessions.final_blocking_session and
                        o.object_id = blocked_sessions.blocked_objects
                  ) where rownum < 11
          )
```

**Comment by ikzelf** [comment]
The idea is to generate lines with a key and a value.

In your case you have 1 key and up to 10 lines/values. That is different. What you could do is to generate serial# for the lines and append them to the original key so you end up with db_locks_01, db_locks_02 etc. You can add those items hard coded to the template, you can also make a lld structure from it. In that case you discover the number of lines and generate these as items that can receive the data.
Hard coded is a bit easier but also might be a bit confusing since you will go and see the 10 lines of output in the 10 items. The higher numbered ones could be old data .....

An other option for me is to strip the linefeeds when writing them to the zbxdb.py output file.

yet an other approach could be to register your most locked objects/addresses and report the # of waiting sessions for them. Zabbix is not so happy with text items. That is why I did only report the top blocker. Doing so makes a graph also more interesting.

**Comment by JustNZ** [comment]
Thanks for your help - we will modify our query to get thing working

Thanks!
