### ISSUE TITLE
Help for monitoring ASM on Oracle 12

### ISSUE THREAD

**Issue by kaisersosset** [ikzelf/zbxdb#88]
Hello, I am studyng your template for some days.

I have no knowledge about oracle and I am really lost about this technology.

I am trying to use this template for monitoring ASM on zabbix. 

The question are these. Should I copy all the content on the servers or just would be needed to add just the checks that I would need? In my case would be just Oracle 12c ASM?

About the config. In zxbora there was a file to config called zbxora.cluster1-ASM.cfg. witch file should I use now in zbxdb?

Thanks for your help.

**Comment by ikzelf** [comment]
Hi,
the best advice I can give you here is to get an oracle dba involved.
Next, I copied the cluster1-ASM.cfg to etc/zbxdb.cluster1-ASM.cfg as an extra example.
zbxdb is meant to do the monitoring of oracle databases from a zabbix proxy of from the zabbix server.
Monitoring from  database node does not make sense, especially when targeting clusters. So install zbxdb on one of the zabbix servers and make sure the zabbix servers can open the listener ports on all the database nodes that are to be monitored.

The example in zbxdb.cluster1-ASM.cfg is especially interesting if you need to monitor an ASM cluster. For a non clustered setup the db_url will be a bit shorter, that's all.

**Comment by ikzelf** [comment]
Could you get this any further?

**Comment by ikzelf** [comment]
I assume dus works now.

**Comment by kaisersosset** [comment]
Hello Ronald, sorry for the delay answering. I am currently at hospital and couldn't test It.

I Will try as soon as possible.

Thanks for tour help and your attention.

Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
