### ISSUE TITLE
How to port query into site.cfg

### ISSUE THREAD

**Issue by matiasba** [ikzelf/zbxdb#90]
Hello!
I'm trying to port some business queries into a site.cfg file. The queries work perfectly when used in the oracle instantclient but for some reason they return ORA-00907: missing right parenthesis when place into a site.cfg file.

Is there any character that may need escaping when making the site.cfg file?
Or maybe there is some additional consideration to take into account?
Cant find anything in the doc about this topic.

**Comment by ikzelf** [comment]
Hi, nice!
use etc/zbxdb_checks/oracle/ebs.cfg as an example. I hope that helps.
Do you happen to have black lines in the SQL?
If you run with debug logging zbxdb.py will list the sql's in the log. You can use -v to increate verbosity (or -vv)

**Comment by matiasba** [comment]
Manage to fix it, one of my subqueris was lacking proper spacing and was being interpreted as a second query. 
Sorry to bother you man!
