### ISSUE TITLE
Request for clarifications

### ISSUE THREAD

**Issue by gianri** [ikzelf/zbxdb#91]
Hi @ikzelf,
This is not a bug report but a request for a little help. I hope I'm in the right place.
Sorry to bother you again, but I need some aid.

For my Oracle DB I created my host "DB_EUSISASST" in Zabbix GUI and linked to it the template "zbxdb_template_v5.xml".
Now I'd like to add some custom queries to ZBXDB, but I'm missing some key concepts...

I can see more than 900 items and 700 triggers associated to my host: all of these are the result of the linked template, or also because ZBXDB runs every single file ".cfg" it finds in the folder "$ZBXDB_HOME/etc/zbxdb_checks/oracle", regardless of the exact name?

I thought to create a ".cfg" file containing my Queries and to add it in the path "$ZBXDB_HOME/etc/zbxdb_checks/oracle": how can I create Items/Triggers linked to this new file (linked to my queries)? Do I need to modify the template for getting this?

Which is the difference between items of these types: "Zabbix Trapper" and "Calculated"? 

I will have to monitor also an Oracle RAC with more instances: I know I need to create only a host for the physical database, but how I can use my custom specific queries only for a precise instance and other custom queries for another specific instance?

Thank you very much for your availability and for your kindness.
Kind regards

**Comment by ikzelf** [comment]
Hi,
the generic queries are found using db_type (oracle), instance_type (rdbms/asm/apx), the version it finds in the connected database (19) and the database role (primary/standby) in finds in the connected database.
Site queries can be specified by using the site_checks (site_checks=your_checks) parameter, where you just give a name. zbxdb will then look into the zbxdb_checks subdirectory for your database and fetch your_checks.cfg

smartest is to create a separate template for your site checks and also attach that to your host.

A trapper item is an item like those that are sent by zbxdb (and ultimately zabbix_sender)
A calculated item is an item that can use other items and expressions to create new values.

zbxdb.py will query the gv$ dynamic views to find metrics for the full cluster. There is no way to limit some queries to a certain instance and others to an other instance.
What is the problem of running all queries using the connected instance? Do you have some tables with very specific access limits or something like that?

**Comment by gianri** [comment]
Mainly because on a specific DB we need to run some queries on specific tables, as on other DBs we need to run different queries on other specific tables. 
So, the way is to create a separate template (cloning for example zbxdb_template_v5.xml, just keeping only the structure)? In this case I can understand there is no way to limit some queries to a certain instance. 

This could be a restriction respect on what we used to do with an old version of Orabbix: with that solution we could create a Host in Zabbix for every single instance, whether they were on physically different DBs or on the same one. Is it no possible doing the same with ZBXDB? Such as creating a zbxdb.{HostName}.cfg file (in $ZBXDB_HOME/etc) for each instance just modifying the db_url parameter with the right Service_name, for example?

**Comment by ikzelf** [comment]
The beauty of zbxdb in combination with RAC is that it monitors the full database from a single connection. I am pretty sure that you can monitor everything you want.
If you run in plugin databases it might a  hassle to make the application tables accessible from the root container. In that case you might need to create an extra config that connects to the application plugin database. Doing so lets you keep the monitoring for the full database. Compared to what you explained about Orabbix you would create configs for different users aiming for different plugin databases. Not for different instances. In my opinion working per instance would create a mess but still, it is possible. In that case you would aim for a vip.

**Comment by ikzelf** [comment]
less typing, that's all for now. If you only have two nodes, it is simple. With more nodes and a lot of dynamics, a scan listener will make it a bit easier to stay connected (or to quickly reconnect if the connected instance/node went down)
In the triggers, if something is instance specific, it will be shown. Sometimes - for example with top blocker - you need to have a bit of knowledge to read it. (it shows the instance# of the top blocker, with the SID and the #of waiters for that session)

**Comment by ikzelf** [comment]
nice.
zabbix does need a key and a value pair. So, you seem to want to count active processes. Now you just need to define a key that can be used to store the result in. If you look into examples you will find constructions where the key is part of the query. If you change this example to "select 'active_sessions', count(*) ...... it will work. In this case you need to create an item 'active_sessions' in zabbix that is going to hold the values. The label 'sessions_active' is just used to make it easier to find problems using the log. It is not part of the key and can't be part of the key since some queries will return multiple keys. Look for example into the p_ts query.

**Comment by ikzelf** [comment]
It looks like RAC is new for you. In that case: you think too much in instances. Since I don't know your configuration it is a bit hard for me to tell what to do but here:
db_url = (DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=RacNodeA-vip)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=RacNodeB-vip)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=Inst1)(SERVER=DEDICATED)))

the address list is OK.
In connect data you specify a service_name that is a/the database, not an instance.

If you specify an instance, your monitoring will stop as soon as that instance stops responding or goes down. That is why it should be a service that is available in at least one but preferably in all instances. It it is in only one instance, make sure that it is transferred to a remaining instance if one goes down. If the connected instance goes down, zbxdb will try to reconnect and hopefully can continue monitoring via an other instance of your cluster. Normally this reconnect is within seconds.

Since the password is for a database user, the password is the same for all instances because they all serve the same database and the user is defined in the database. If you have pluggable databases connect to the root container with a global account. That way you can discover and monitor all pdb's from within the root container, if needed.

**Comment by gianri** [comment]
Hi Ikzelf,
I'm having performance issues on my DB and I was thinking about minimizing Queries of ZBXDB, so to leave active only the main ones. 
To  reduce the resource load of my target DB, is it enough to disable the items associated with the host on Zabbix? Or should I remove the correspondents Queries from the CFG checks file (primary.11.cfg - for my version)?

**Comment by ikzelf** [comment]
In latest data you can see the response times of the queries. Most will be sub-second and they will not do any harm for your database. There is one query that can be influenced by a filled recycle bin and that is the one behind p_ts. Most of the times this is solved by purging the dba recycle bin. First check the response times so you know which query could be the/a culprit.

**Comment by gianri** [comment]
In Latest Data I don't have the Response Time: it could be because my Zabbix version is 5.0 rather than the latest?

**Comment by ikzelf** [comment]
There should be ..... check application zbxdb with keys like "zbxdb[query,*,ela]  (and also status)
No matter what version of zabbix you use, this is part of the self monitoring system in zbxdb.

**Comment by gianri** [comment]
Ok, I found these keys and values:
zbxdb[query,checks_05m,obj.stat,ela]     1s 700.69ms
zbxdb[query,checks_05m,t_ts,ela]           1s 277.2ms
zbxdb[query,checks_60m,p_ts,ela]           1m 9.41ms
zbxdb[query,checks_60m,,ela]                  1m 728.16ms

This does mean that to decrease the load on my DB I should Disable these Items?
Thanks, as always

**Comment by ikzelf** [comment]
Disabling then in the GUI won't do anything here, except that the items will ignore the data that is sent to them. As I already expected: the culprit is zbxdb[query,checks_60m,p_ts,ela] 1m 9.41ms. It runs every 5 mins.
The solution is to purge the dba recycle bin. After that it normally runs sub second again.

a workaround is to move it in primary.11.cfg to checks_60m so it is executed once an hour, or completely remote the query. Doing so takes away your resource monitoring since this query tracks your tablespace usages, in my opinion one of the more useful things to monitor.

How does this item look in a graph? Since when is the ela > 1s?

**Comment by gianri** [comment]
Looking in graphs, I can see that items "zbxdb[query,checks_05m,obj.stat,ela]" and "zbxdb[query,checks_05m,t_ts,ela]" present different peaks, but only in few occasions are > 1s.
Different is for "zbxdb[query,checks_60m,p_ts,ela]" and "zbxdb[query,checks_60m,,ela]": they have always been > 1m (m, not s)

**Comment by ikzelf** [comment]
It would be smart to check with your local dba about the recycle bin. With a little luck it can be purged and that will solve the issue. When oracle objects are dropped, they end up in the recycle bin and keep using space. Sometimes it is kept as a way to revert a drop action but more often than not, the bin can be purged after a few hours.
PURGE DBA_RECYCLEBIN;

**Comment by gianri** [comment]
Okay, good to know that the dba_recyclebin is the weakness of this query: probably we should schedule the purge once a month, more or less, depending of how many drops...
The culprit Query zbxdb[query,checks_60m,p_ts,ela] is that in attach of this message? It is the only one I can see similar (p_ts) in primary.11.cfg, but it is under "minutes 60" section, not under "minutes 5" (if it runs every 5 mins). 
Where am I wrong?
I fully agree with you that the monitoring of tablespace usage is one of the more important things and, for this reason, I'd like to get it run every 5 or 10 mins as maximum, but without worrying about blocking the DB

**Comment by gianri** [comment]
Sorry... here is the attach
[CulpritQuery.txt](https://github.com/ikzelf/zbxdb/files/7601405/CulpritQuery.txt)

**Comment by ikzelf** [comment]
Yes, you are right. Because most permanent tablespaces are quite regular in their growth I have it run once an hour. T_ts is more frequent.

**Comment by gianri** [comment]
Perfect.
I ran an AWR report when my DB was suffering and the Query that was top in the following lists was that in attach:
- User I/O Wait Time
- CPU Time
- Elapsed Time

I can't find this query out in Primary.11.cfg, even if it is zbxdb related because it uses the Zabbix schema. Probably this is another simple question for you, but can you help me to understand ?

[QueryInAWR.txt](https://github.com/ikzelf/zbxdb/files/7601830/QueryInAWR.txt)

**Comment by ikzelf** [comment]
Do I understand correctly that you have combined the zabbix schema in your monitored database?
That is a bit different that what I expected. The zabbix database, when used for more than a handful of devices will be busier than most application databases. I will check the query asap.

**Comment by ikzelf** [comment]
The query you found in AWR is strange for me. Which user is running it and from what machine? zbxdb has a query to find the top blocking session. That is zbxdb[query,**checks_01m,blocked**,ela] which does a pretty good job in identifying the most problematic session (the one blocking most other sessions). The awr query you found certainly is one that checks for locking but it is not run by zbxdb.
If this query is worrying you, make sure you find the source and stop it. zbxdb is very resource friendly.

Did you by any chance also try to deploy one of the original zabbix oracle templates on this database? If that is the case, you should be able to disable the item with this query. That might be the only advantage that the original zabbix database template has: all config in the GUI.

**Comment by gianri** [comment]
My Zabbix runs on a dedicated machine with its own mysql DB.
From the report of "Oracle Tuning  Advisor" in Toad about the query found in AWR, I can see that it is related to the schema name "zabbix".
My ZBXDB is configured (in the file ZBXDB.MyMonitoredDB.cfg) to connect with the user zabbix.
The only template associated in zabbix for my monitored DB is that of zbxdb: ​/home/zbxdb/zbxdb/zbxdb_template_v5.xml
Very strange... let me check the AWR of another monitored DB with the same zbxdb/template...

**Comment by ikzelf** [comment]
Maybe this query comes from cloud control? This query generates a list intended to be read by someone. Can you see from which machine the query comes?

**Comment by gianri** [comment]
Yes, I confirm, I ran the AWR report on another monitored DB with same template/checks, and I found the same query (it has the same SQL ID) being at the top of the worst lists (wait/cpu/elapsed time).
I'm not getting any complaints from users of this last DB, probably because the dedicated machine is more powerful

**Comment by ikzelf** [comment]
There is one extra thing that zbxdb does when connecting to a database: it sets the module to zbxdb so you can recognise weather a query comes from zbxdb.py or an other tool. Do you have site_checks in your configuration?

**Comment by gianri** [comment]
Cloud cannot be because we don't have any service in Cloud yet.
Monitoring the sessions I see that it is coming from Zabbix machine... but why?
In attach you can find my custom check file, the same for all both DB (I changed the extension from .cfg to .txt)
[my_checks_DBRAC.txt](https://github.com/ikzelf/zbxdb/files/7602746/my_checks_DBRAC.txt)

**Comment by ikzelf** [comment]
Your custom checks won't be a problem I think. One of the many names is cloud control other names for the same tool are OEM, Oracle Enterprise Manager, CC ..... What is listed in the column 'module' for the sessions running that nice query?

**Comment by gianri** [comment]
In Module it's written JDBC Thin Client.
zabbix in machine, and ZABBIX in username columns

**Comment by ikzelf** [comment]
So there is some Java app running that query. Could be enterprise manager. zbxdb.py uses the regular sqlnet libraries and identifies itself in the module as zbxdb.py. Maybe change the password for the zabbix user? Someone will start complaining about that.....

**Comment by ikzelf** [comment]
Could you track down which tool is running the queries?

**Comment by gianri** [comment]
Hi @ikzelf, I haven't changed zabbix user's password yet, but I'll do it for sure in the next days if nothing comes up. I'll keep you updated. 
Thanks for all

**Comment by gianri** [comment]
Hi @ikzelf, the  culprit was a old installation of Orabbix that was still running on our old zabbix Server!

**Comment by ikzelf** [comment]
hah, nice that you could solve this!
