### ISSUE TITLE
Query p_ts gets a negative value

### ISSUE THREAD

**Issue by gianri** [ikzelf/zbxdb#92]
Hi Ronald, 
sorry to bother you again, but I have a very strange behavior about the monitoring of tablespaces: ZBXDB gets a negative value of "Usedbytes" for only a specific tablespace, so that on Zabbix I see the error (Not Supported - Value "-82372870144" of type "string" is not suitable for value type "numeric (unsigned)") associated to the corrisponding related item 

I tried the same Query ("p_ts" of primary.11.cfg file) in Toad and in fact the value obtained is negative:

p_ts[MyDB,MyTBS,usedbytes] = -81433346048
But the real usedbytes value is = 409GB

Have you an idea why this appens? For all others tablespaces ZBXDB seems to get the correct value of "Usedbytes".

**Comment by ikzelf** [comment]
And how is it with this query:
SELECT   'p_ts['||d.name||','||tablespace_name||','||
           CASE
             WHEN k = 1 THEN 'filesize]'
             WHEN k = 2 THEN 'maxsize]'
             WHEN k = 3 THEN 'usedbytes]'
             WHEN k = 4 THEN 'pctfree]'
             WHEN k = 5 THEN 'pctfreeMAX]'
           END key
  ,        CASE
           WHEN k = 1 THEN file_size
           WHEN k = 2 THEN file_max_size
           WHEN k = 3 THEN file_size - file_free_space
           WHEN k = 4 THEN ROUND(file_free_space / file_size * 100,2)
           WHEN k = 5 THEN round((file_max_size - (file_size - file_free_space))/decode(file_max_size,0,1,file_max_size) * 100,2)
           END value
  FROM   ( --
         select t1.tablespace_name,
               t1.file_size,
               t1.file_max_size,
               t2.file_free_space
          from (  select t.tablespace_name, sum (f.bytes) file_size, sum (case when f.autoextensible = 'NO' then f.bytes else greatest (f.bytes, f.maxbytes) end) file_max_size
                    from dba_tablespaces t, dba_data_files f
                   where t.CONTENTS = 'PERMANENT' and f.tablespace_name = t.tablespace_name
                group by t.tablespace_name) t1,
               (  select f.tablespace_name, sum (f.bytes) file_free_space
                    from dba_free_space f
                group by tablespace_name) t2
         where t1.tablespace_name = t2.tablespace_name(+)
       )
  cross JOIN   ( SELECT LEVEL k FROM dual CONNECT BY LEVEL <= 5 ) k
  cross join v$database d
/

This might have a little performance issue with dba_free_space in it ....

**Comment by ikzelf** [comment]
I think this should also fix the performance problem (I hope since I have no v11 databases at hand to check this)

SELECT   'p_ts['||d.name||','||tablespace_name||','||
             CASE
               WHEN k = 1 THEN 'filesize]'
               WHEN k = 2 THEN 'maxsize]'
               WHEN k = 3 THEN 'usedbytes]'
               WHEN k = 4 THEN 'pctfree]'
               WHEN k = 5 THEN 'pctfreeMAX]'
             END key
    ,        CASE
             WHEN k = 1 THEN file_size
             WHEN k = 2 THEN file_max_size
             WHEN k = 3 THEN file_size - file_free_space
             WHEN k = 4 THEN ROUND(file_free_space / file_size * 100,2)
             WHEN k = 5 THEN ROUND((file_free_space + (file_max_size - file_size)) / file_max_size * 100,2)
             END value
    FROM   ( --
           select t1.tablespace_name,
                 t1.file_size,
                 t1.file_max_size,
                 t2.file_free_space
            from (  select t.tablespace_name, sum (f.bytes) file_size, sum (case when f.autoextensible = 'NO' then f.bytes else greatest (f.b  ytes, f.maxbytes) end) file_max_size
                      from dba_tablespaces t, dba_data_files f
                     where t.CONTENTS = 'PERMANENT' and f.tablespace_name = t.tablespace_name
                  group by t.tablespace_name) t1,
    -- AU: Oracle 11-12 has performance issue with dba_free_space
    -- Original select:
    --               (  select f.tablespace_name, sum (f.bytes) file_free_space
    --                    from dba_free_space f
    --                group by tablespace_name) t2
                 (  select a.tablespace_name, sum (a.bytes) file_free_space
                      FROM   SYS.dba_data_files b, SYS.dba_free_space a
                      WHERE a.tablespace_name = b.tablespace_name
+                       and a.file_id         = b.file_id
                      GROUP BY a.tablespace_name, b.tablespace_name) t2
           where t1.tablespace_name = t2.tablespace_name(+)
         )
    cross JOIN   ( SELECT LEVEL k FROM dual CONNECT BY LEVEL <= 5 ) k
    cross join v$database d
/

if you see this is correct, I will add it to the config and push it to GitHub.
Thanks for catching this.

**Comment by gianri** [comment]
The first one you wrote is fine! It gets the correct value! 
About performance issue... could be good schedule a purge dba_recyclebin?

Let me try this second one now...

**Comment by gianri** [comment]
Perfect, also the second one is working fine and no negative values are returned.
Should I check the elapsed time of this last Query to be sure about the performance, or there is not need?

Thanks to you Ronald

**Comment by ikzelf** [comment]
The first one is a copy from primary.10.cfg. An other user reported a performance problem with it in v11 and gave a fix. It's a bit of a pity that the fix included a cartesian product, that I now removed with ( and a.file_id = b.file_id) So now it works for table spaces having multiple datafiles too. If you see a significant difference if execution times, I would vote for the quickest.

And yes, maintaining the recycle bin will always help.

**Comment by ikzelf** [comment]
Did you find a significant difference in elapsed time?

**Comment by gianri** [comment]
The second one, that should be quicker, is slower in reality:  >500msec
The first one is faster instead: 200-250msec

Can it be?

**Comment by ikzelf** [comment]
I guess it depends on the database layout and contents. Choice looks simple: the original query from v10.

**Comment by gianri** [comment]
Ok, thanks a lot again!!
