### ISSUE TITLE
Typo in primary.10.cfg file

### ISSUE THREAD

**Issue by thimself** [ikzelf/zbxdb#94]
Hi,

I noticed a typo in the Primary.10.cfg file when trying to add 10g databases to Zabbix.

Starting from line 39 you have this block:
```
rman.lld: select distinct(object_type) "{#OBJ_TYPE}" from v$rman_status where operation like 'BACKUP%'
          union all
					select 'usermanaged' from v$backup where change  # > 0 and file# = 1
```
At line 41 it should be:
`select 'usermanaged' from v$backup where change# > 0 and file# = 1`
There is 2 spaces between "change" and "#"

-thimself

**Comment by ikzelf** [comment]
Thanks for catching this ..... one of my vim plugin does something funny when writing, that I not always see.
