### ISSUE TITLE
@ikzelf Good day!

### ISSUE THREAD

**Issue by Heloiseboanerges** [ikzelf/zbxdb#96]
@ikzelf Good day!
I'm experiencing a similar error when trying to monitor my ASM instance... 
It seems that, the login is not created as SYSDBA... :(

![image](https://user-images.githubusercontent.com/40353290/166483235-dc173765-9cf4-4159-84d7-b07f1431bff7.png)

I've tried using the cfg file for zbxdb.oracle-cluster1-ASM.cfg and the zbxdb.odb.cfg.... changing the connection string... but no clue:

[zbxdb]
db_url = //172.24.130.197:1521/+ASM
username = zabbix_mon
password =
db_type = oracle
db_driver = cx_Oracle
instance_type = asm
role = sysdba
out_dir = $HOME/zbxdb_out
site_checks =
hostname = P6PRODASM
checks_dir = etc/zbxdb_checks
password_enc = 

![image](https://user-images.githubusercontent.com/40353290/166483881-34738fb3-8e7f-4a26-8467-ba26c99e1bb6.png)

Is there something I'm missing? For the DB instance works as expected (is a dataguard standby, so, the sysdba has been granted for the user...)

_Originally posted by @Heloiseboanerges in https://github.com/ikzelf/zbxdb/issues/80#issuecomment-1116229480_

**Comment by ikzelf** [comment]
Can you connect with sqlplus providing the same credentials? If sqlplus can connect, so can zbxdb. (Which version of zbxdb are you using (a few lines up in the log shows the version))

**Comment by Heloiseboanerges** [comment]
Hi! finally, my DBA and I managed to complete the connection :) , thank you a lot for the support.

On the other hand, I have a doubt about the alertlog template, does it work with Oracle installed in Windows? 

Thanks!

**Comment by ikzelf** [comment]
Nice that you got it working. Do you see omissions in the documentation on this? If so, feel free to improve it and create a pull request for it.

The alertlog monitoring could be used for windows also but might need some tweaking. I have no windows servers so it’s a bit hard for me to adjust that.
