### ISSUE TITLE
Monitoring dataguard enabled database

### ISSUE THREAD

**Issue by thimself** [ikzelf/zbxdb#97]
Hi,

First thanks for this great product, have been using it for some time with great success.
But i'm running into a problem when monitoring a dataguard enabled database.

Database in question has primary and secondary node (CDB/PDB configuration) and the secondary is kept in sync with dataguard. This means that the node in question is in mounted state.
I am able to monitor this configuration, but i am getting an alert from 2nd node that it is not responding. There is a explanation attached to this alert "could be down but could also be caused when no parallel slaves are available in the remote instance[s]"

Obviously as it is in mounted state, it might be because of user privileges. In config i have "role = normal".
The question is that do i have to run monitoring with elevated sysdba -like privileges in this case that i get proper database status from 2nd node?

**Comment by ikzelf** [comment]
Yes, this is the case since the database is in mounted state there is no other option if you can not use active data guard, in which case the normal role can also work. This is something I can not help since this is how oracle made this. If you see/know smarter options, please enlighten me.

**Comment by ikzelf** [comment]
Not all queries run in the same interval. Some queries run every minute, some only a few times a day or only during a new connect. This could be a reason that it takes a bit longer to see a status change. Can you find the query that provides the data? If so, check the minutes parameter for the section where that query is defined. That will tell you how long you need to wait for a status change (or restart the zbxdb.py process)
Are you using zabbix_proxies? That might also add time for items that are dynamically discovered.

**Comment by thimself** [comment]
Hi,

We are using a proxy to monitor this target. I will clear and unlink, then let it run for 24h and see what it picks up. I will update you when this is done.

**Comment by ikzelf** [comment]
With a proxy the lld will pass discovered items via the proxy to the server. During the next proxy config cache reload the proxy will receive the discovered items and start accepting the values for those items. Default this is down once an hour. If you happen to have a dynamic discovered item that is samples once every 6 hours ..... it will take at least 6 hours before the change comes through.

**Comment by ikzelf** [comment]
Could it be that after the switch-over the databases are not monitored by the correct config file[s]? With that I mean: a database should be processed by the config file that fits the database_role in v$database. (primary_XX.cfg of standby_XX.cfg) The database_role is only fetched during the logon to the instance. At this moment I am not sure about when the instances are restarted (or at all) during the switch-over. The used files are also uploaded to zabbix in the 	
zbxdb[checks, items for your databases. In that case, the session of your monitoring user is older than the switchover time.

**Comment by thimself** [comment]
Hi,

I have disconnected the problematic one manually by renaming cfg file and then naming it back. Will have to see if it helps.
Monitoring is done by one host in zabbix, primary and secondary are connected through the same connection string with FAILOVER parameter and both nodes mentioned there as host1 and host2.

But i think it should "reset" manually when a failover happens. Im not sure if we are doing something wrong. But at least in my mind this should be the right way of connecting to dataguard enabled database(s) and monitoring them through a single target host.

**Comment by ikzelf** [comment]
I think the problem is that I tried to make connection management as efficient as possible and only re-connect when the instance or the monitoring host is restarted. What I think you could do it to implement a [9.1.5 Role Transition Triggers](https://docs.oracle.com/en/database/oracle/oracle-database/19/sbydb/managing-oracle-data-guard-role-transitions.html#GUID-18E84C50-79D7-4158-A5B8-FD0C3EEEB8B6) that terminates the session of the zbxdb.py process. It is recognisable in v$session.
zbxdb.py will re-connect, detect the current database role and select the correct checks file depending on the role.

One question: you control your connection using sqlnet. Do you expect to always connect to the primary node? If that is the case, you should not need the sysdba connection since that is only needed when the database is not open.

**Comment by thimself** [comment]
Hi,

I will look into these triggers.

We are always connecting to the primary database, we do not need to have open connections to standby database. We connect directly to CDB so that we can get for example backup information for all PDB databases.
In this case yes, we do not need elevated privileges.

**Comment by ikzelf** [comment]
And you run 1 zbxdb.py instance from a monitoring server that connects to both databases, depending on the database role as defined in you connect string/tns_alias?

**Comment by thimself** [comment]
Yes, one instance and connection string what connects to both databases. Most of the cases its like this:

db_url = (DESCRIPTION =(FAILOVER=ON)(LOAD_BALANCE=OFF)(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = SERVER1)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = SERVER2)(PORT = 1521)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = SERVICE.domain)))

**Comment by thimself** [comment]
Also noticed another problem with target(s).
At the moment one of these databases what we are discussing at the moment is also getting an repeating information about cancelled checks in logs:
2022-07-07 10:57:29,820___main___30_zbxdb cancel_sql checks_60m p_ts
2022-07-07 10:57:29,821___main___30_zbxdb canceled   checks_60m p_ts

**Comment by ikzelf** [comment]
OK, if you use one single zbxdb.py instance that connect to the database using db_url = (DESCRIPTION =(FAILOVER=ON)(LOAD_BALANCE=OFF)(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = SERVER1)(PORT = 1521))(ADDRESS = (PROTOCOL = TCP)(HOST = SERVER2)(PORT = 1521)))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = SERVICE.domain))) it should work when using normal user role.
Can you show the item and values that tell you there is a problem? You use this a bit different than what I thought about. I used to monitor the databases as 2 independent databases and I also had active data guard available at that time ..... But we can make this work, sure about that.

For the timeout on p_ts: more often than not this is a problem with a large recycle bin. Could you empty that? Normally it runs sub second.

**Comment by thimself** [comment]
_For the timeout on p_ts: more often than not this is a problem with a large recycle bin. Could you empty that? Normally it runs sub second._

This solved timeout issue.

To solve that "connection issue" i clicked unlink + clear and it has not yet popped up again. I'm keeping my eye out for it or any other similar cluster to show this same problem, if we can then get to the issue itself and see how to fix it.
So give me few days and i will follow this issue and report whats happening.

**Comment by thimself** [comment]
Hi,

Tried this with another cluster target, this time it is ASM cluster, but the principle is same.

Current configuration:
- both nodes monitored separately, 2 .cfg files and both have their respective node addresses and hostnames.
- 2 targets in Zabbix

cfg:
node1 = db_url = //simple.address1.domain:1521/+SERVICE, hostname = asm_node1
node2 = db_url = //simple.address2.domain:1521/+SERVICE, hostname = asm_node2

zabbix:
Both nodes have their own host created and template linked. (Should there be 1 host and both .cfg's pointed to 1 node?)

Alerts:
zbxdb: asm_node1 +SERVICE2 not responding since xxx
zbxdb: asm_node2 +SERVICE1 not responding since xxx

Service name "+SERVICE" is present in both and nodes have their own SID's (+SERVICE1 and +SERVICE2 as an example)
Because it is ASM, its in "active-active" configuration and both monitoring targets are working fine and receiving all needed data. Problem is that even in this configuration because its "sniffing" the other SID (as in 2nd node) it will start alerting that it cant connect to it. 

I have also tried this with connection string with FAILOVER or without, but with 2 addresses added. This will connect fine too, but same alerts persist. This is most likely because it will always connect to the first address listed and stay connected because its "working". In this case i only had 1 host in Zabbix.

How can we make this work with clusters? Dataguard and ASM to be exact. I have tried this with RAC and its working at the moment.

**Comment by ikzelf** [comment]
‘Cluster’ means shared storage and RAC?
If not you have 2 separate asm installations.

**Comment by thimself** [comment]
Sorry for the delay, busy as always.

Queries are running fine and data is updating normally. I have run into to issues with for example databases running on RAC as well. In this configuration we have the normal one host configured in Zabbix and in .cfg file we have connection configured using SCAN fqdn address.

In this example RAC is One Node RAC, it has 2 physical nodes but database is running on one node at a time. It can be switched over to second node normally and in some cases like updates/upgrades it is switched over.

Problem comes with this that when database(s) are switched over, they will show up in Zabbix that its running on node 2 and when its switched over back to primary node, its running on node 1. Ok, this is normal situation. 
But now Zabbix is showing that database@node2 is not responding since X minutes. <- database is on node 1 like it should.

This let me to believe that problem is in how databases are detected and how Zabbix alerts from them. For some reason its handling this situation like node is its own server even when its a part of RAC node and is the "cold" side when database(s) are on node 1.

This is same kind of behaviour what i saw earlier with Dataguard enabled databases when the primary database is running either on of the nodes and secondary is just in DG enabled state (mounted or in ADG situation read only).

I am not that good with Zabbix itself so im at a loss how to solve this with this probe/template. Do you have any ideas?

**Comment by ikzelf** [comment]
This is more like an issue for race one node .... and not so much with dataguard.
The problem could be that
[auto_discovery_60]
minutes: 60
inst.lld: select distinct (inst_name) "{#INST_NAME}"
            from (select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances
                  union
                  select instance_name from gv$instance)

discovers all instances so it can track them all.
In your case you only want to track one instance and not all (me guessing).
Problem is: how can I recognise this?

can you show the output from:
select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances;

and also from:
select instance_name from gv$instance;

I never had the pleasure working with ray one node, only with regular rac where all instances are supposed to be running all time.

This query will fill the items:
inst.uptime: select 'inst['||instance_name||',uptime]' key,(sysdate -startup_time)*60*60*24 val from gv$instance;
can you show the output of this uptime query as well?

The trigger is on the inst[{#instance_name},uptime] item.

**Comment by thimself** [comment]
Issue is with both Dataguard and RAC one node databases and behaviour seems the same.
We also monitor more traditional RAC setups and when both or multiple nodes are up as they are reachable -> no "ghost" alarms.

So here are queries which are done in both Dataguard and RAC one node databases.

Active data guard database:

First query:
```
select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances;

no rows selected
```

----

Second query did not work, original query:
inst.uptime: select 'inst['||instance_name||',uptime]' key,(sysdate -startup_time)6060*24 val from gv$instance;

Fixed it like this, but I think you can make it work with only "*" added in after first parenthesis in sysdate section.
```
select 'inst['||instance_name||',uptime]' key,((sysdate - startup_time)*6060*24) val from gv$instance;

inst[NODEB,uptime]         1309847.12
```


-----

Third query:
```
select distinct (inst_name) "{#INST_NAME}" from (select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances union select instance_name from gv$instance);

{#INST_NAME}
--------------------------------------------------------------------------------
NODEB
```


RAC one node:

First query:
```
select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances;

RAC_NODE_1
```

-----

Second query:

```
select 'inst['||instance_name||',uptime]' key,((sysdate - startup_time)*6060*24) val from gv$instance;

inst[RAC_NODE_1,uptime]	2126681.25
```

-----

Third query:
```
select distinct (inst_name) "{#INST_NAME}" from (select rtrim(substr(regexp_replace(inst_name, '[^[:print:]]', ''),instr(inst_name,':')+1)) inst_name from v$active_instances union select instance_name from gv$instance);

RAC_NODE_1
```

As we can see here, it is always connected to active node as it should. But in both of these cases we have switched over active node for maintenance reasons and after this the "backup" node raises an alarm and it can't be closed.

And yes, we would like to track active node only because secondary is not reachable as it is basically a standby node at this point. 
Connection string is configured in Dataguard with both nodes as servers with failover option. In RAC one node connection goes through SCAN ip as it is controlled by RAC.
On RAC we have a problem with ASM monitoring and it is presenting it self in a same way. ASM service is available through its own listener and it has no VIP/SCAN address thus connection is done by node IP + shared service name. It detects that there is a second node but connection is to first node -> second node has an alert "not responding since xxx". This is exactly the same alert we see with these previous ones too.

**Comment by thimself** [comment]
While checking these i found one possible problem how the connection is handled from monitoring agent to server. I will check if this helps with some of these problems what we are encountering. I will keep you up to date.

**Comment by thimself** [comment]
One of these problematic (DG Enabled) database is now configured differently from connection point of view, but i wont know before next switchover if it worked.

This still leaves us with RAC one node, this target is giving us an alarm about node number 2 not being reachable, well it is not because it's RAC one node -> second node is standby.

Any idea how to fix this in Zabbix?

**Comment by thimself** [comment]
Closing this old issues, solved with Zabbix modifications.
