### ISSUE TITLE
LOG_ARCHIVE_DEST is not VALID with ALTERNATE target

### ISSUE THREAD

**Issue by thimself** [ikzelf/zbxdb#98]
Hi,

I have another support request open, but i'm opening a lower priority bug report for archive log dest monitoring.

In few configurations we need to use different settings for "LOG_ARCHIVE_DEST#" value and monitoring is picking it up as an error/not valid configuration.

Configuration is: 
LOG_ARCHIVE_DEST_1
VALID
D:\primary\path

LOG_ARCHIVE_DEST_2
ALTERNATE
D:\path\to\secondary

Monitoring is picking this up as "zbxdb: arl_dest[database_name,LOG_ARCHIVE_DEST_2] is not VALID", "ARL destination not in (VALID(0) and DEFERRED(1))"

configuration for this LOG_ARCHIVE_DEST_2 as ALTERNATE is intentional.

Thanks again :)

**Comment by ikzelf** [comment]
does 
select i.instance_name "{#INST_NAME}",d.dest_name "{#ARL_DEST}"
            from gv$archive_dest d
            , gv$instance i
            , v$database db
            where d.status != 'INACTIVE'
            and   d.inst_id = i.inst_id
            and   db.log_mode = 'ARCHIVELOG'

give results as expected?

same for
select 'arl_dest['|| i.instance_name||','||d.dest_name||',status]', ''||decode (d.status,'VALID',0,'DEFERRED',1,'ERROR',2,3)
            from gv$archive_dest d
            , gv$instance i
            , v$database db
            where d.status != 'INACTIVE'
            and   d.inst_id = i.inst_id
            and db.log_mode = 'ARCHIVELOG'
          union all
          select 'arl_dest['|| i.instance_name||','||d.dest_name||',sequence]', ''||d.log_sequence
            from gv$archive_dest d
            , gv$instance i
            , v$database db
            where d.status != 'INACTIVE'
            and   d.inst_id = i.inst_id
            and db.log_mode = 'ARCHIVELOG'
          union all
          select 'arl_dest['|| i.instance_name||','||d.dest_name||',error]', '"'||d.error||'"'
            from gv$archive_dest d
            , gv$instance i
                , v$database db
            where d.status != 'INACTIVE'
            and   d.inst_id = i.inst_id
            and db.log_mode = 'ARCHIVELOG'

do you have a suggestion how to change?

**Comment by ikzelf** [comment]
The trigger prototype for the arl_dest.lld discovery rule in the template is:
{template zbxDB:arl_dest[{#INST_NAME},{#ARL_DEST},status].last(30m)}>1

ARL destination not in (VALID(0) and DEFERRED(1))
What status do you have from above query?
does the query return a value for the %_error field?

**Comment by thimself** [comment]
Hi,

First query:
Database
LOG_ARCHIVE_DEST_1

Database
LOG_ARCHIVE_DEST_2

Second query:
arl_dest[database,LOG_ARCHIVE_DEST_1,status]
0
arl_dest[database,LOG_ARCHIVE_DEST_2,status]
3
arl_dest[database,LOG_ARCHIVE_DEST_1,sequence]
32889
arl_dest[database,LOG_ARCHIVE_DEST_2,sequence]
0
arl_dest[database,LOG_ARCHIVE_DEST_1,error]
""
arl_dest[database,LOG_ARCHIVE_DEST_2,error]
""

From these we can see that DEST_2 returns value 3. 
I cannot find any exact information that what number correlates to what setting.
[https://docs.oracle.com/en/database/oracle/oracle-database/19/sbydb/LOG_ARCHIVE_DEST_n-parameter-attributes.html#GUID-B04FC22C-F0B0-440F-BAF4-182EE547FCC1](url)
Oracle documentation does not state anything regarding about numbers returned when running this query.

I am not the best Zabbix master, but looking at line 324 in primary.19.cfg there is:
"decode (d.status,'VALID',0,'DEFERRED',1,'ERROR',2,3)"
Does this mean that in monitoring when DEST_2 returns value 3, it is viewed as an error?
Also looking at the query, error section is empty.

**Comment by thimself** [comment]
> The trigger prototype for the arl_dest.lld discovery rule in the template is:
{template zbxDB:arl_dest[{#INST_NAME},{#ARL_DEST},status].last(30m)}>1

>ARL destination not in (VALID(0) and DEFERRED(1))
What status do you have from above query?
does the query return a value for the %_error field?

Is this what you were looking for?

zbxdb: arl_dest[database,LOG_ARCHIVE_DEST_2] is not VALID,
Operational data: UNK (3)

**Comment by ikzelf** [comment]
See [8.34 V$ARCHIVE_DEST in Database Reference](https://docs.oracle.com/en/database/oracle/oracle-database/21/refrn/V-ARCHIVE_DEST.html#GUID-B70F0435-96AE-4AB4-9329-F035188C413F)
What is the status in your database?

select 'arl_dest['|| i.instance_name||','||d.dest_name||',status]', ''||decode (d.status,'VALID',0,'DEFERRED',1,'ERROR',2,3) zabbix_key, d.status
            from gv$archive_dest d
            , gv$instance i
            , v$database db
            where d.status != 'INACTIVE'
            and   d.inst_id = i.inst_id
            and db.log_mode = 'ARCHIVELOG'

Zabbix is a bit more efficient in storing numbers, compared to storing strings so the character statuses are translated to a number using the decode.

**Comment by thimself** [comment]
Hi,

Result:
ZABBIX_KEY                               STATUS
---------------------------------------- ---------
arl_dest[database,LOG_ARCHIVE_DEST_1,status]
0                                        VALID

arl_dest[database,LOG_ARCHIVE_DEST_2,status]
3                                        ALTERNATE

**Comment by thimself** [comment]
Hi,

Imported new configs and template, unlinked one of the problematic targets and started from "fresh" with it.
Now the alert does not pop up anymore and it looks like its working.
One thing what i want just to double check before closing this.

It looks like this in "Latest data" in zabbix:
arl_dest[database_LOG_ARCHIVE_DEST_2_status]
07/21/2022 02:59:21 PM ERROR (2)

Note that this does not raise an alarm, but it shows its status as "ERROR"

Trigger looks like:
{SERVER:arl_dest[database,LOG_ARCHIVE_DEST_2,status].last(30m)}>2
ARL destination not in (VALID(0) , DEFERRED(1) and ALTERNATE(2))

**Comment by ikzelf** [comment]
It looks like the value mapping is not updated. It should look like:
zbxdb arl_dest	0 ⇒ OK
1 ⇒ DEFERRED
2 ⇒ ALTERNATE
3 ⇒ ERRROR
4 ⇒ DISABLED
5 ⇒ BAD PARAM
6 ⇒ FULL
7 ⇒ unknown
and can be found via de GUI administration/Genereral, select value mapping from the top left dropdown and search for "zbxdb arl_dest"
You can manually adjust it, if the list is not complete. If so: zabbix bug. The list is complete in the xml file.

**Comment by thimself** [comment]
Hi,

This might be because there is still the older profile available and enabled on other targets. I wonder it will break when i change this.

I think i have to migrate all the targets to the new template first.

**Comment by ikzelf** [comment]
If all database are now monitored using the new SQL in the primary.XX.sql they already receive the new values and they are able to use the new values in the map. The databases that still use the old template will keep firing a trigger when the arm status is ALTERNATE. So, yes, unlink/link would be OK.

**Comment by thimself** [comment]
Replaced configs and made a new template. Had to manually fix mappings, but that was easy.
Linked all monitored targets with new template and did the switch without clearing data. If it causes problems, then i will clear it again.

Seems to be working at the moment. Thank you for the help.
